### ISSUE TITLE
Action bar hide/show is jumpy + PreferenceFragment

### ISSUE THREAD

**Issue by easyaspi314** [anthonycr/Lightning-Browser#155]
When Lightning is in full screen mode, there is a jump of the content. This, I believe is from ActionBar.hide(); causing the content to readjust. You can see this by scrolling down/up a hair and let go quickly. 
I think a way to fix this is to jump on the Material train with AppCompat and a Toolbar, which is **much** more flexible than an Action Bar. I might be able to help, as well as make your life easier with that SettingsActivity using a PreferenceFragment, if I get time, so you do not need layouts for settings.

**Comment by karolba** [comment]
Why is this issue closed? ActionBar is still jumpy.

**Comment by easyaspi314** [comment]
i was going to split it.
