### ISSUE TITLE
[feature request] 'request desktop site' menu option

### ISSUE THREAD

**Issue by vthriller** [anthonycr/Lightning-Browser#157]
This one should be pretty easy: just toggle user agent to something desktop-ish

**Comment by JonasCz** [comment]
Would be nice, just like in AOSP browser.  Might need some way to store the setting for each website though.

**Comment by easyaspi314** [comment]
I think you can do it this way:

1. Put an onOptionsItemSelected method to put the value into
SharedPreferences (using the same value as the one in the settings) and
call a method.
2. Create that method to 1. Get the webview and 2. Set the user agent. Call
that method in onResume, too.

Haven't tested it but I *think* that would work.

**Comment by anthonycr** [comment]
This is probably doable. There need to be specifics on how it's implemented. I see a couple ways to handle it

1. as @easyaspi314 points out, it could simply modify the current preference to view pages as desktop, but that would get used by all webviews as currently whenever a webview is resumed, it rechecks all its settings and resets them. 
2. it could be a tab specific thing, where it just changes the current tab to desktop for the remainder of the session.

Chrome does it on a site specific basis where it remembers your preference for each site, but I don't want to do this as it requires modifying the way the history works and means storing more data for each site visited which seems rather unnecessary for a mobile browser.

**Comment by easyaspi314** [comment]
A possible implementation?

menu/main.xml
```xml
    <item android:id="@+id/desktop" android:title="@string/toggle_desktop" />
```
BrowserActivity.java
```java
public boolean isDesktopUa = false;
...
@Override
public boolean onOptionsItemSelected(MenuItem item) {
...
case R.id.desktop
    toggleUserAgent(this, mCurrentView.getWebView());
    break;
...
}

@Override
public boolean onPrepareOptionsMenu(Menu menu) {
...
        final MenuItem uaSwitcher = menu.findItem(R.id.desktop);
        uaSwitcher.setChecked(isDesktopUa);
}
...
public void toggleUserAgent(Context context, WebView view) {
    WebSettings settings = view.getSettings();

    String desktop = Constants.DESKTOP_USER_AGENT;
    String default = settings.getDefaultUserAgent(context);
        if (view == null) {
            return;
        }
            if (settings.getUserAgentString().equals(default)) {
                isDesktopUa = true;
                settings.setUserAgentString(deskop);
            } else {
                isDesktopUa = false;
                settings.setUserAgentString(default);
            }
    refreshOrStop():
    invalidateOptionsMenu();
}
```
**This is a simplified version of the way the AOSP Browser does it (10 times more complex than it needs to be):**

<i>/src/com/android/browser/</i>[Controller.java](https://github.com/android/platform_packages_apps_browser/blob/fe15d2a0bf7b10a21a53a4e286f6bad5ccbce7d3/src/com/android/browser/Controller.java)
```java
private TabControl mTabControl;
public Controller(Activity browser) {
        mSettings = BrowserSettings.getInstance();
        mTabControl = new TabControl(this);
...
}
// Line 1536
@Override
public boolean onOptionsItemSelected(MenuItem item) {
...
            case R.id.ua_desktop_menu_id:
                toggleUserAgent();
                break;
...
}
// Line 1685
    @Override
    public void toggleUserAgent() {
        WebView web = getCurrentWebView();
        mSettings.toggleDesktopUseragent(web);
        web.loadUrl(web.getOriginalUrl());
    }

// Line 1817
    @Override
    public WebView getCurrentWebView() {
        return mTabControl.getCurrentWebView();
    }
```

<i>/src/com/android/browser/</i>[TabControl.java](https://github.com/android/platform_packages_apps_browser/blob/fe15d2a0bf7b10a21a53a4e286f6bad5ccbce7d3/src/com/android/browser/TabControl.java)
```java
    /**
     * Return the current tab's main WebView. This will always return the main
     * WebView for a given tab and not a subwindow.
     * @return The current tab's WebView.
     */
    WebView getCurrentWebView() {
        Tab t = getTab(mCurrentTab);
        if (t == null) {
            return null;
        }
        return t.getWebView();
    }
```

<i>/src/com/android/browser/</i>[BrowserSettings.java](https://github.com/android/platform_packages_apps_browser/blob/fe15d2a0bf7b10a21a53a4e286f6bad5ccbce7d3/src/com/android/browser/BrowserSettings.java)
```java
/**
 * Can probably just get a boolean since we don't really need all this complexity
 */
    private WeakHashMap<WebSettings, String> mCustomUserAgents;
// Line 493
    public void toggleDesktopUseragent(WebView view) {
        if (view == null) {
            return;
        }
        WebSettings settings = view.getSettings();
        if (mCustomUserAgents.get(settings) != null) {
            mCustomUserAgents.remove(settings);
            settings.setUserAgentString(USER_AGENTS[getUserAgent()]);
        } else {
            mCustomUserAgents.put(settings, DESKTOP_USERAGENT);
            settings.setUserAgentString(DESKTOP_USERAGENT);
        }
    }
```

**Comment by JonasCz** [comment]
Maybe the option could be associated with a particular bookmark, perhaps by adding a checkbox to the 'edit bookmark' dialog. Shouldn't be so complicated to store an extra boolean in the bookmarks database...

**Comment by anthonycr** [comment]
This feature has been added as a toggle in the bookmark drawer.
