### ISSUE TITLE
Action bar hide/show is jumpy. (split from #155)

### ISSUE THREAD

**Issue by easyaspi314** [anthonycr/Lightning-Browser#163]
Split from #155
When Lightning is in full screen mode, there is a jump of the content. This, I believe is from ActionBar.hide(); causing the content to readjust. You can see this by scrolling down/up a hair and letting go quickly.

I have been trying to toy with it, and I think that using the AppCompat Toolbar in place of an ActionBar is best. I have also thought that [this library](https://github.com/ksoichiro/Android-ObservableScrollView) would work.

**Comment by anthonycr** [comment]
Yes, I need to overlay the actionbar over the webview content. I'm going to fix it when I either transition to the Toolbar for Lollipop or build my own actionbar (this might end up being easier than using the toolbar widget)

**Comment by anthonycr** [comment]
Complete
