### ISSUE TITLE
PreferenceFragment (split from #155)

### ISSUE THREAD

**Issue by easyaspi314** [anthonycr/Lightning-Browser#164]
Split from #155 
When looking at the code, I noticed that you are using a settings screen that was made out of a bunch of layouts. This could be done easier by using a [PreferenceFragment](http://developer.android.com/reference/android/preference/PreferenceFragment.html), which does all the work for you. I have been working on this, and I can upload my work so far, but it does not run, and there were some commits that happened while I was working on it, and no translations.

**Comment by pejakm** [comment]
@easyaspi314: Could you please commit your current work to your fork, so I can have a peak? :) Thanks.

**Comment by easyaspi314** [comment]
Yeah, I'm trying, but Git hates me.  I will edit the files online. I hate
doing that, but oh, well.

**Comment by pejakm** [comment]
Dear God, don't do that, learn git, it's hard at all. :D

**Comment by easyaspi314** [comment]
Well i got most of it done, but it was yelling at me because I had not
updated it since the bunch of recent commits. See the
preference-fragment-test branch in
https://github.com/easyaspi314/Lightning-Browser.

**Comment by anthonycr** [comment]
This is a good idea that I should have done a long time ago.

**Comment by DF1E** [comment]
You may have to look at this: https://github.com/DF1E/Lightning-Browser/commit/d5ff7abe2616ae974356983c24ea51578a418e6b
It's a working an simple example of preference activty.

Screenshots:
https://www.dropbox.com/s/jatb5i4maxz0zbu/settings1.png?dl=0
https://www.dropbox.com/s/stwk6f46h9do36r/settings2.png?dl=0

**Comment by anthonycr** [comment]
Completed
