### ISSUE TITLE
Dev branch build failed.

### ISSUE THREAD

**Issue by ageback** [anthonycr/Lightning-Browser#172]
I'm not sure whether my build env. has problems. I can build the old master branch before. But after I switching to dev branch I can't build successfully. No matter with IntellijIdea or eclipse. A lot of attrs in values\styles.xml and values-v21\styles.xml cannot be found. Part of the error log:

[2015-01-31 13:39:11 - LightningBrowserDev] D:\workspace1\LightningBrowserDev\res\values-v21\styles.xml:28: error: Error: No resource found that matches the given name: attr 'colorAccent'.
[2015-01-31 13:39:11 - LightningBrowserDev] 
[2015-01-31 13:39:11 - LightningBrowserDev] D:\workspace1\LightningBrowserDev\res\values-v21\styles.xml:26: error: Error: No resource found that matches the given name: attr 'colorPrimary'.
[2015-01-31 13:39:11 - LightningBrowserDev]

**Comment by kuc** [comment]
Builds of dev branch are failing from some time now:
https://travis-ci.org/anthonycr/Lightning-Browser/builds

**Comment by anthonycr** [comment]
Yeah the dev branch fails to build because it requires two support libraries (appcompat-v7 and palette-v7) which are included as jars in the app but need to be imported into the workspace and referenced by the project as library projects. If you import those support libraries as projects and set them as libraries to lightning it should build. I still need to figure out how to get that to work with the Travis CI build though.

**Comment by ageback** [comment]
Well, after imported appcompat-v7 and palette-v7 as library projects it builds successfully. But at runtime got FC.  I think it was caused by this:

02-01 17:15:39.185: E/AndroidRuntime(32066): Caused by: java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.getDrawable
02-01 17:15:39.185: E/AndroidRuntime(32066): 	at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:133)
02-01 17:15:39.185: E/AndroidRuntime(32066): 	at android.support.v7.internal.widget.TintTypedArray.getDrawable(TintTypedArray.java:62)
02-01 17:15:39.185: E/AndroidRuntime(32066): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:248)
02-01 17:15:39.185: E/AndroidRuntime(32066): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:190)

But I have updated to the latest support library. I've no idea what to do now.

**Comment by anthonycr** [comment]
Make sure in the Order and Export tab of the properties for the appcompat library, you have the android-support-v4 and v7-appcompat jars checked. It's weird and I had trouble getting it working right myself. It would probably work better if I just switched to Android Studio/gradle but I should probably wait until the lightning 4.0 release is done

**Comment by ageback** [comment]
This issue can be closed now. Finally I built and ran Dev branch successfully with Eclipse.
