### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by shorty66** [anthonycr/Lightning-Browser#177]
Hello,
I think it would be nice to have a "dark mode", where the tabs overview, bookmarks and adress bar would be colored dark to preserve night vision.
I think most important are tabs and bookmarks, as these are quite big bright surfaces.

**Comment by JonasCz** [comment]
:+1:  Btw, If you enable incognito mode, The action bar and overflow menu go dark, so it should not be too hard to do this for the panels too...

**Comment by anthonycr** [comment]
The only reason I hesitate to do this is that if I implement it that eventually a changeable theme other than light dark will creep into the app so I don't want to be forced to do that. I do understand the need for the dark drawers though as the light theme annoys a lot of people (fwiw I like light themes). That said... I was thinking about this yesterday and there might be a solution:

Has anyone used QuickPic? They have a really interesting and stupid simple solution that just gets around the whole thing by not putting a background on the drawer but letting the content bleed through. Check it out and let me know what you think.

**Comment by anthonycr** [comment]
Here's a screen shot of an incomplete implementation of a transparent tabs drawer just to demonstrate what I was talking about in previous comment
![screenshot_2015-02-23-18-46-44](https://cloud.githubusercontent.com/assets/1966779/6340427/11601ce8-bb8d-11e4-9c78-ef80971f9810.png)

**Comment by JonasCz** [comment]
It looks cool, but if you are going to implement a changeable theme anyway (Can we set any color we want?) Then it is not really necessary.

**Comment by shorty66** [comment]
I don't see why a transparent drawer would be any better than a solid colored dark one.
I don't like transparency in often used ui components, as it distracts from the important content.
On top of that, this transparent theme would also add another theme option - why is this better than having a drak theme?

If a changeable theme is planned anyways, you could always remove the temporary dark theme code then...

**Comment by anthonycr** [comment]
This feature has been added.
