### ISSUE TITLE
Address bar becomes transparent on some sites.

### ISSUE THREAD

**Issue by karolba** [anthonycr/Lightning-Browser#178]
For example, on [Stack Exchange's Ask Ubuntu](http://askubuntu.com). The favicon of that site: ![askubuntu.com's favicon](http://cdn.sstatic.net/askubuntu/img/favicon.ico) 

Example of the bug in a screenshoot: ![first screenshoot](https://cloud.githubusercontent.com/assets/6043048/6031271/2eae473c-abfe-11e4-9100-ceabd3dd11e5.png)

This address bar becomes even more unreadable when that favicon is used for a site with a dark background: 
![second screenshoot](https://cloud.githubusercontent.com/assets/6043048/6031500/2a40eaf4-ac00-11e4-8ff7-bd0317986244.png)

**Comment by shorty66** [comment]
As a quick workaround turn of the 'color mode' option.

**Comment by anthonycr** [comment]
Wow, thanks for this report, looks like there is a bug in the Palette library as it should never return a transparent color or black as neither of those is a "vibrant" color. I'll have to add a work around for that bug. As was mentioned, simply turning off color mode will prevent this from happening until I get the code fixed to reject transparent and dark colors.

**Comment by karolba** [comment]
For the record, the color of the address bar on the second screenshoot is not black, but transparent.

**Comment by anthonycr** [comment]
@karolba ahh okay, well that makes it a little simpler to handle. I'll just check if the favicon color I get is transparent or not and then adjust accordingly. Seems the palette API is returning transparent in rare cases

**Comment by karolba** [comment]
@anthonycr The Ask Ubuntu's favicon (![favicon](http://askubuntu.com/favicon.ico)) has white right in its center, I think that is causing the transparency. Wouldn't it be better if the address bar's color was the most used color from a favicon, instead of the color from the favicon's center? Ask Ubuntu would then get an orange address bar, as it should.

**Comment by anthonycr** [comment]
@karolba yeah it should grab the orange, but I'm using this API (https://developer.android.com/reference/android/support/v7/graphics/Palette.html) and asking it for the "Vibrant" color so I'm not sure what algorithm Google employs to grab the color. It sometimes grabs a minority color that is brighter than another one present in an icon, but in this case it definitely should have grabbed the orange as it's the only vibrant color. What's interesting is that the API says it returns an RGB value (no mention of alpha) so I am not sure why it would be giving a transparent color.

**Comment by anthonycr** [comment]
In case anyone is interested...

The palette API returns an Alpha value of 0xff for every single image I've seen except for the favicon from askubuntu.com. Instead, it returns an orange color (the correct color) with an alpha value of 0x06 which is basically completely transparent. The odd thing is that the palette.getVibrantColor() method I'm using to retrieve the color is only supposed to return an RGB value... with no alpha value... 

I decided to just bit mask the value it returns with 0xff000000 and it works, no more transparency and the color for askubuntu is orange as expected.

**Comment by kuc** [comment]
Weird, maybe it's bug in converting semi-transparent ICO files to bitmap.

**Comment by anthonycr** [comment]
Oh well, maybe I'll try to report it as a bug. Anyway, fixed in commit https://github.com/anthonycr/Lightning-Browser/commit/ab134a8927e594d6c81bceab0db8d2f190c98d07
