### ISSUE TITLE
support geo: urls

### ISSUE THREAD

**Issue by shorty66** [anthonycr/Lightning-Browser#179]
Geo: urls should be handled correctly. Example urls can be found in the wikipedia article [1] and should open as a geo: intent.

[1] https://en.m.wikipedia.org/wiki/GeoURL

**Comment by anthonycr** [comment]
They are handled fine for my on my Nexus 4 running 5.0.1. They open correctly in Google Maps. What version of Android are you seeing this problem on and do you have a mapping application installed that can handle this intent.

If you look at the code, the app actually asks the system if there are any apps that can handle the url and if there is one it asks the user if they want to open it.

See:
https://github.com/anthonycr/Lightning-Browser/blob/master/src/acr/browser/lightning/LightningView.java#L876
and
https://github.com/anthonycr/Lightning-Browser/blob/master/src/acr/browser/lightning/IntentUtils.java#L36

**Comment by shorty66** [comment]
Well, never mind. I just noticed that the links work right now.
I did not really change anything, so i am not able to reproduce the bug - lightning gave me a 404.

I am using android 4.4 on a sony xperia zr by the way.

**Comment by anthonycr** [comment]
Okay, well that's good to hear. It could have been that you clicked on the screen just as the "open with" popup was about to show up (canceling it) and so it just tried to load the url. That's happened to me before. Let me know if it's a problem you see consistently in the future.
