### ISSUE TITLE
colliding sidebars

### ISSUE THREAD

**Issue by shorty66** [anthonycr/Lightning-Browser#184]
When one of the sidebars is currently open and the other sidebar is quickly opened they may collide.
If this happens both sidebars are closed.
A workaround is to open the second sidebar slowly but i think it would be better if the opening procedere would not stop upon collision.

I admit its a rather unusual setting, but it happened twice to me today.

**Comment by anthonycr** [comment]
I'm going to work around this by just locking the closed drawer while the other drawer is open, that's how it worked previously and it prevented these collisions just fine. Of course this means you won't be able to directly open tabs when bookmarks are open and vice versa as it adds an extra swipe.

swipe to close --> swipe to open other drawer

**Comment by shorty66** [comment]
I think that is a good solution.

**Comment by anthonycr** [comment]
Fixed in commit https://github.com/anthonycr/Lightning-Browser/commit/313f9fb105468356edca1bed4735f9af13eec01a
