### ISSUE TITLE
Add option to show the complete address in the URL box

### ISSUE THREAD

**Issue by JonasCz** [anthonycr/Lightning-Browser#192]
It would be nice to have an option (in settings) to show the full url in the URL box, and not just the domain name. Maybe also add an option to show webpage title?

**Comment by kuc** [comment]
:+1:

**Comment by JonasCz** [comment]
_
          |)`
          | |
          | |_____
         /    (]__)
        /    (]___)
       /    (]___)
          ___(]_)
         /
       /

**Comment by anthonycr** [comment]
Sure! I'll add a dropdown option in settings somwhere, three options
- domain (default)
- full URL
- page title

**Comment by shorty66** [comment]
The desktop version of firefox shows the full url in grey text except for the domain. I think this is a quite useful approach.
Page title is already visible in the tabs overview and not really needed i think. Perhaps the title of the currently open tab could scroll through slowly to allow reading of longer titles.

**Comment by JonasCz** [comment]
@Shorty, it may not be needed, by it's nice to have the option anyway.  Full URL in gray is a interesting idea

**Comment by anthonycr** [comment]
done
