### ISSUE TITLE
Quick Control

### ISSUE THREAD

**Issue by lth8284** [anthonycr/Lightning-Browser#194]
Slide thumb from left or right edge to open quick control like quick control feature in Default Browser.

**Comment by JonasCz** [comment]
Slide from left / right edge is already used for the bookmarks / tabs panels...

**Comment by lth8284** [comment]
Quick control includes tabs so you can add quick control at the tabs panel. Do you try quick control in AOSP Browser lollipop? The option in the Lab. I don't like when I turned on, it hide the url panel cos it include the URL there.

**Comment by anthonycr** [comment]
Sorry, as mentioned these gestures are used to open the navigation drawers. This will not be implemented.
