### ISSUE TITLE
Version 4.0.8a crashes immediately with "NoClassDefFoundError"

### ISSUE THREAD

**Issue by utack** [anthonycr/Lightning-Browser#213]
The newest version (4.0.8a from F-Droid) is crashing for me on startup.
Devices: Snapdragon 800 with Android 5.1.1 (Cyanogenmod 12.1), Snapdragon S4 with Android 5.1.0 (Google factory image)
```
E/AndroidRuntime( 6454): FATAL EXCEPTION: main
E/AndroidRuntime( 6454): Process: acr.browser.lightning, PID: 6454
E/AndroidRuntime( 6454): java.lang.NoClassDefFoundError: android.support.v7.app.g
E/AndroidRuntime( 6454): 	at android.support.v7.app.d.a(Unknown Source)
E/AndroidRuntime( 6454): 	at android.support.v7.app.AppCompatActivity.K(Unknown Source)
E/AndroidRuntime( 6454): 	at android.support.v7.app.AppCompatActivity.onCreate(Unknown Source)
E/AndroidRuntime( 6454): 	at acr.browser.lightning.ThemableActivity.onCreate(Unknown Source)
E/AndroidRuntime( 6454): 	at acr.browser.lightning.BrowserActivity.onCreate(Unknown Source)
E/AndroidRuntime( 6454): 	at acr.browser.lightning.MainActivity.onCreate(Unknown Source)
E/AndroidRuntime( 6454): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 6454): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 6454): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
E/AndroidRuntime( 6454): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
E/AndroidRuntime( 6454): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime( 6454): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 6454): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6454): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6454): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime( 6454): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6454): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6454): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 6454): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/ActivityManager(  780):   Force finishing activity 1 acr.browser.lightning/.MainActivity

```

**Comment by pejakm** [comment]
Same thing here. I'll compile it myself later to see if this is some kind of compilation bug in F-Droid.

**Comment by pejakm** [comment]
Furthermore, I cannot compile it. :(

**Comment by krt16s** [comment]
A clean checkout and build like
````
git clone git@github.com:anthonycr/Lightning-Browser.git
cd Lightning-Browser
git submodule update --init --recursive
./setup-ant.sh
ant release
````
crashes for me, too. even checking out 4.0.3.

For reference, FDroid's issue (with logcat) is here: https://gitlab.com/fdroid/fdroiddata/issues/206

**Comment by DF1E** [comment]
Try to uninstall the old version and make a clean install

**Comment by ildar** [comment]
it doesn't help. I tried
>
>

**Comment by krt16s** [comment]
Same for 4.0.9. @DF1E Could you check if my steps above SHOULD create a working apk and if they actually DO so?

**Comment by anthonycr** [comment]
Try updating to the latest support library, the problem looks like it can't find AppCompatActivity which is only found in the latest AppCompatLibrary.

**Comment by aelmahmoudy** [comment]
@anthonycr I just built it with the latest support library (I checked the android-support-v7-appcompat.jar, and I did find the AppCompatActivity class), yet it still crashes.

**Comment by ildar** [comment]
Does the exception look the same? can you check the adb logcat?
>
>

**Comment by anthonycr** [comment]
I'm switching to Android Studio and the problem will be fixed. Eclipse managed to get the code into a weird state where it allowed me to use parts of the old and new app compat libraries without giving any errors and without crashing the app... no idea how it managed that, but it did lol. I switched to Android Studio and got a crash so I fixed the problem in the code (some line in styles.xml needed to be present, but I have no idea why my build in Eclipse isn't broken)

**Comment by krt16s** [comment]
Most IDEs are doing quite some automagic, but AS should give us a clean gradle build. To package the new version for FDroid I even started to migrating it to gradle on our side. I am glad to have this done on your end :). So thanks for looking into this issue!

**Comment by anthonycr** [comment]
@krt16s if you want to check it out, I've gotten a partially working gradle build up on the dev branch.

**Comment by obifur** [comment]
I'm not sure if this is the same problem - if so you may ignore it.. I'm using the latest playstore version 4.0.9a on Android 4.1.1:

05-06 07:05:46.274   302   509 I ActivityManager: START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=acr.browser.barebones/.MainActivity u=0} from pid 601

05-06 07:05:46.324   302  7011 I ActivityManager: Start proc acr.browser.barebones for activity acr.browser.barebones/.MainActivity: pid=14618 uid=10122 gids={3003, 1015, 1028}

05-06 07:05:46.404 14618 14618 I dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method acr.browser.barebones.BrowserActivity.K

05-06 07:05:46.434 14618 14618 I dalvikvm: Could not find method android.webkit.CookieManager.removeAllCookies, referenced from method acr.browser.barebones.BrowserActivity.h

05-06 07:05:46.604 14618 14618 I dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method acr.browser.barebones.ei.getView

05-06 07:05:46.624 14618 14618 I dalvikvm: Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method acr.browser.barebones.LightningView.a

05-06 07:05:46.624 14618 14618 I dalvikvm: Could not find method android.webkit.WebSettings.getDefaultUserAgent, referenced from method acr.browser.barebones.LightningView.a

05-06 07:05:46.624 14618 14618 I dalvikvm: Could not find method android.webkit.WebSettings.setMediaPlaybackRequiresUserGesture, referenced from method acr.browser.barebones.LightningView.a

05-06 07:05:46.624 14618 14618 I dalvikvm: Could not find method android.webkit.WebSettings.setMixedContentMode, referenced from method acr.browser.barebones.LightningView.a

05-06 07:05:46.624 14618 14618 I dalvikvm: Could not find method android.webkit.WebSettings.setMixedContentMode, referenced from method acr.browser.barebones.LightningView.a

05-06 07:05:46.664 14618 14618 I dalvikvm: Could not find method android.webkit.WebView.evaluateJavascript, referenced from method acr.browser.barebones.cu.onPageFinished

05-06 07:05:46.674 14618 14618 I dalvikvm: Could not find method android.webkit.WebResourceRequest.getUrl, referenced from method acr.browser.barebones.cu.shouldInterceptRequest

05-06 07:05:46.884   302   338 I ActivityManager: Displayed acr.browser.barebones/.MainActivity: +574ms

05-06 07:05:47.464   105   105 I DEBUG   : pid: 14618, tid: 14618, name: owser.barebones  >>> acr.browser.barebones <<<

05-06 07:05:47.724   302  7011 I WindowState: WIN DEATH: Window{4291c448 acr.browser.barebones/acr.browser.barebones.MainActivity paused=false}

05-06 07:05:47.724   302  1410 I ActivityManager: Process acr.browser.barebones (pid 14618) has died.

05-06 07:05:47.724   302  1410 W ActivityManager: Force removing ActivityRecord{428954c8 acr.browser.barebones/.MainActivity}: app died, no saved state

---- 06.05.2015 07:06:06 ----
