### ISSUE TITLE
problem with tir

### ISSUE THREAD

**Issue by treakiandroid** [anthonycr/Lightning-Browser#218]

**Comment by treakiandroid** [comment]
Problem with tor notification.

Sorry, issue got send befor i was done...

Everytime i open up lightning i got messaged about that i have installed orbot and if i would like to use it. Everytime i click no. Could you please add an setting to save this choice??

Thanks

**Comment by anthonycr** [comment]
Hmmm, the setting should be in there. I have orbot installed and I don't have this problem. What version of Android are you on?

**Comment by treakiandroid** [comment]
Now i have upgraded to latest fdroid version and there is the missing button. I hope alsovthat the annoying message box wont appare again. Thanks a lot for the help
