### ISSUE TITLE
change subscribed adblock list

### ISSUE THREAD

**Issue by treakiandroid** [anthonycr/Lightning-Browser#219]
There is just one switch to switch add blocking feature on and off. But no way to set to which adblocking list its got subscribed. I guess you are using easylist but i would like to set the lists in use by my self.

Thanks in advance and keep up the good work

**Comment by anthonycr** [comment]
I'm actually just blocking a list of hosts in the browser, no lists are used so until I change the adblock function to something different, we can't use lists :(

**Comment by treakiandroid** [comment]
Ok, than please inform users about rhe way it is working.

**Comment by kuc** [comment]
@treakiandroid You can just read source code, it's not something hidden.
https://github.com/anthonycr/Lightning-Browser/blob/master/app/src/main/assets/hosts.txt
