### ISSUE TITLE
auto cleanup feature

### ISSUE THREAD

**Issue by treakiandroid** [anthonycr/Lightning-Browser#220]
Could you add a feature to delete Cookie's every night, every reboot and/or any manual browser close. Could you also add a list of exceptions for Cookie behaviour like Firefox dose? Thanks in advance

**Comment by treakiandroid** [comment]
Looks like a clear cookies at close appeared after my last fdroid update thanks for that. Why there was notching written about in the release notes??

**Comment by kuc** [comment]
I'm sure that "clear cookies (and cache) at close" option is available for months.
