### ISSUE TITLE
Android Lollipop Crash on Start

### ISSUE THREAD

**Issue by deavmi** [anthonycr/Lightning-Browser#221]
It crashes on launch on Android Lollipop.

**Comment by anthonycr** [comment]
Are you using the version from F-Droid?

**Comment by deavmi** [comment]
@anthonycr Yes :smile:

**Comment by anthonycr** [comment]
That's the problem then haha. The build on f-droid is broken (see the issue you commented on), hopefully I can get it fixed.

**Comment by deavmi** [comment]
@anthonycr Okay. :smile: Thanks. I will close this issue then.

**Comment by krt16s** [comment]
This should be fixed in 4.0.10a

**Comment by deavmi** [comment]
I noticed now that a build has been removed (the broken one) and there are three builds available for download now.
