### ISSUE TITLE
NetCipher is breaking the build [dev branch] - gradle changes

### ISSUE THREAD

**Issue by anthonycr** [anthonycr/Lightning-Browser#226]
libnetcipher is used by the browser, and it requires the support-v4 library to build properly. The owners of the repository have decided to add the support-v4 .jar file to the project in their gradle file instead of pulling in a version from maven. This conflicts with the appcompat-v7 library I'm using in gradle, because that relies on the latest support-v4, so it pulls in the latest .jar from maven and then there are two conflicting support-v4 .jars being included in the build.

Locally, the fix is to open the build.gradle file in libnetcipher and replace the lines:
```
// compile 'com.android.support:support-v4:21.0.3'
// compile 'com.madgag.spongycastle:core:1.51.0.0'
compile fileTree(dir: 'libs', include: '*.jar')
```
with
```
compile 'com.android.support:support-v4:22.1.1'
compile 'com.madgag.spongycastle:core:1.51.0.0'
compile files('libs/httpclientandroidlib-1.2.1.jar')
```
NOTE: The version of the support library must be the same version used to build the app (currently 22.1.1.

However, I don't know how to fix this at the repo level without forking the NetCipher libary and applying the fix myself using that as a reference. Also, this fix cant work with Travis CI because it pulls in the libnetcipher library from git and so changes to the libraries gradle file made locally won't apply.

Anyone have any ideas?

**Comment by anthonycr** [comment]
I created a pull-request on the NetCipher library, but until then, the build is sort of broken

**Comment by krt16s** [comment]
Imho you can add dependencies for subprojects in your project and gradle should be able to pick the newest only. But I haven't done that myself.

**Comment by anthonycr** [comment]
Hmmm I'll look into that, still a gradle n00b.

**Comment by anthonycr** [comment]
Woohoo, think this is all fixed thanks to some new commits to Netcipher

**Comment by anthonycr** [comment]
Fixed.
