### ISSUE TITLE
Use jsoup from mavenCentral/jcenter

### ISSUE THREAD

**Issue by krt16s** [anthonycr/Lightning-Browser#233]
Instead of `compile files('libs/jsoup-1.8.1.jar')` use `compile "org.jsoup:jsoup:1.8.1"`.

**Comment by kuc** [comment]
:+1: , that's the whole point of using build tools.

**Comment by anthonycr** [comment]
Truuuueee :+1:

**Comment by anthonycr** [comment]
Done. https://github.com/anthonycr/Lightning-Browser/pull/234
