### ISSUE TITLE
[regression] URL bar is not auto-hidden any more

### ISSUE THREAD

**Issue by ildar** [anthonycr/Lightning-Browser#236]
as in pre-material versions
Also IMHO it better be optional (through Settings).

**Comment by shorty66** [comment]
It works and is optional.
You have to activate 'fulscreen' under 'display settings' to auto hide adressbar.

**Comment by ildar** [comment]
Isn't "Fullscreen" word mean something else? E.g. hiding status bar and
such?
>
>

**Comment by karolba** [comment]
What version are you using? There's literally an option called "Hide status bar".

**Comment by ildar** [comment]
You're right, I was confused by options I see.
Anyway isn't "Hide address bar" more clear then "Fullscreen" ?
Thanks for answering!

**Comment by shorty66** [comment]
yeah, i had that confused earlier as well. I think "Hide address bar" would be more clear.
