### ISSUE TITLE
Searches when I enter a URL

### ISSUE THREAD

**Issue by CharString** [anthonycr/Lightning-Browser#246]
when I enter a URL of the form

   http://machine:1234/

or

   https://machine:5678/

I don't expect to be taken to a duckduckgo search for that string.

**Comment by karolba** [comment]
The same when you have a hostname that doesn't include a dot. `http://localhost/` doesn't work and `http://mycustomhostname/` where mycustomhostname is defined in /system/etc/hosts also doesn't work.

**Comment by CharString** [comment]
On 23 May 2015 11:42:37 CEST, Karol Baraniecki <notifications@github.com> wrote:
>The same when you have a hostname that doesn't include a dot.
>`http://localhost/` doesn't work and `http://mycustomhostname/` where
>mycustomhostname is defined in /system/etc/hosts also doesn't work.

I think that's exactly what I meant! 'machine' being a name in the dns of my home router. It didn't occur to me that a dot changes the behaviour.

In principle I think any well-formed rfc1738 url should be handled as a url, not as a search term.
Maybe perhaps, when the scheme is a protocol that lightning doesn't know how to handle.
-- 
Chris Wesseling
Centrum Wiskunde & Informatica (CWI)
https://www.cwi.nl/people/ccw

**Comment by anthonycr** [comment]
Problem was with URL validation you were right. I was using some VERY simple validation and definitely not conforming to the RFC spec. I've updated the url validation to correctly check the url using code from the AOSP browser so this will be all fixed in the next version.

**Comment by anthonycr** [comment]
Fixed in https://github.com/anthonycr/Lightning-Browser/commit/68f5c4fb45eb99ef3a8cf6ebd99568f3abf05824
