### ISSUE TITLE
Add Korean translation

### ISSUE THREAD

**Issue by halcyonest** [anthonycr/Lightning-Browser#250]
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation">

    <string name="app_name">라이트닝</string>
    <string name="drawer_open">탐색 서랍 열기</string>
    <string name="drawer_close">탐색 서랍 닫기</string>
    <string name="action_websearch">웹 검색</string>
    <string name="action_refresh">새로고침</string>
    <string name="action_new_tab">새 탭</string>
    <string name="action_share">공유</string>
    <string name="action_history">기록</string>
    <string name="action_bookmarks">즐겨찾기</string>
    <string name="action_add_bookmark">즐겨찾기 추가</string>
    <string name="action_copy">링크 복사</string>
    <string name="action_forward">앞으로</string>
    <string name="google">Google</string>
    <string name="settings">설정</string>
    <string name="location">위치 접근</string>
    <string name="password">암호 저장</string>
    <string name="agent">User Agent</string>
    <string name="history">기록 지우기</string>
    <string name="email">이메일 보내기</string>
    <string name="flash">Adobe Flash 사용</string>
    <string name="mobile">모바일 형식으로 보기</string>
    <string name="desk">데스크탑 형식으로 보기</string>
    <string name="custom">임의의 User Agent 형식으로 보기</string>
    <string name="home">홈페이지</string>
    <string name="settingshelp">설정은 새 탭에만 적용됩니다</string>
    <string name="fullscreen">전체 화면 모드</string>
    <string name="java">JavaScript 사용</string>
    <string name="saveTab">잃어버렸을 경우 탭 복원</string>
    <string name="settings_title">설정</string>
    <string name="download">다운로드 위치</string>
    <string name="settings_advanced">고급 설정</string>
    <string name="source">소스 코드</string>
    <string name="license">라이센스</string>
    <string name="github">github.com/anthonycr/Lightning-Browser</string>
    <string name="apache">Apache License 2.0</string>
    <string name="title_activity_new_settings">NewSettings</string>
    <string name="action_settings">설정</string>
    <string name="version">앱 버전</string>
    <string name="cache">종료할 때 캐시 지우기</string>
    <string name="reflow">Text reflow 사용</string>
    <string name="block">이미지 차단</string>
    <string name="window">웹사이트가 새 창을 열도록 허용</string>
    <string name="cookies">쿠키 사용</string>
    <string name="importbookmarks">브라우저로부터 즐겨찾기 가져오기</string>
    <string name="size">글자 크기</string>
    <string name="recommended">권장합니다</string>
    <string name="search">검색 엔진</string>
    <string name="search_hint">검색</string>
    <string name="wideViewPort">Wide viewport 사용</string>
    <string name="overViewMode">개요 보기 모드에서 페이지 불러오기</string>
    <string name="restore">잃어버린 탭을 시작할 때 복원</string>
    <string name="stock_browser_unavailable">기본 브라우저가 감지되지 않음</string>
    <string name="stock_browser_available">지원되는 기본 브라우저 감지됨</string>
    <string name="fullScreenOption">브라우징 도중에는 상태 표시줄 숨기기</string>
    <string name="clear_cookies">브라우저 쿠키 지우기</string>
    <string name="dialog_image">이 이미지로 무엇을 할까요?</string>
    <string name="action_download">다운로드</string>
    <string name="action_open">열기</string>
    <string name="dialog_link">이 링크로 무엇을 할까요?</string>
    <string name="dialog_title_share">이 페이지 공유</string>
    <string name="dialog_bookmark">이 즐겨찾기로 무엇을 할까요?</string>
    <string name="action_delete">삭제</string>
    <string name="action_blank">빈 페이지</string>
    <string name="agent_default">기본값</string>
    <string name="agent_desktop">데스크탑</string>
    <string name="agent_mobile">모바일</string>
    <string name="agent_custom">임의의 UA</string>
    <string name="title_search_engine">검색 엔진</string>
    <string name="action_ok">확인</string>
    <string name="dialog_download">파일을 다운로드할까요?</string>
    <string name="action_cancel">취소</string>
    <string name="title_warning">경고</string>
    <string name="dialog_adobe_dead">아쉽게도 Google이 몇가지 바꿔놓은 부분이 있기 때문에, Adobe Flash는 Android 4.4 이상에서는 작동하지 않습니다.</string>
    <string name="dialog_adobe_not_installed">Adobe Flash Player가 감지되지 않았습니다.\nFlash Player를 설치하세요.</string>
    <string name="dialog_adobe_unsupported">Adobe Flash는 Andoid 4.2 이상을 지원하지 않기 때문에 충돌이 발생할 수 있습니다. Flash를 사용할 때는 오류 보고서를 보내지 마세요.</string>
    <string name="title_user_agent">User Agent</string>
    <string name="title_download_location">다운로드 위치</string>
    <string name="title_custom_homepage">임의의 홈페이지</string>
    <string name="action_webpage">웹페이지</string>
    <string name="dialog_reflow_warning">아쉽게도 Google이 몇가지 바꿔놓은 부분이 있기 때문에, Text Reflow 기능은 Android 4.4 이상에서는 작동하지 않습니다.</string>
    <string name="title_clear_history">기록 지우기</string>
    <string name="title_clear_cookies">쿠키 지우기</string>
    <string name="dialog_history">모든 브라우저 기록을 지울까요?</string>
    <string name="dialog_cookies">모든 브라우저 쿠키를 지울까요?</string>
    <string name="action_yes">예</string>
    <string name="action_no">아니오</string>
    <string name="title_text_size">글자 크기</string>
    <string name="size_largest">가장 크게</string>
    <string name="size_large">크게</string>
    <string name="size_normal">보통</string>
    <string name="size_small">작게</string>
    <string name="size_smallest">가장 작게</string>
    <string name="title_error">오류</string>
    <string name="dialog_import_error">즐겨찾기를 가져올 브라우저가 감지되지 않았습니다.</string>
    <string name="hint_title">제목</string>
    <string name="hint_url">URL</string>
    <string name="title_edit_bookmark">즐겨찾기 편집</string>
    <string name="action_edit">편집</string>
    <string name="action_incognito">새 사생활 보호 탭</string>
    <string name="hello_world">Hello world!</string>
    <string name="action_homepage">기본값</string>
    <string name="action_back">뒤로</string>
    <string name="action_find">페이지에서 찾기</string>
    <string name="download_pending">다운로드 시작\u2026</string>
    <string name="cannot_download">\"http\" 또는 \"https\" URL만 다운로드할 수 있습니다.</string>
    <string name="download_no_sdcard_dlg_title" >SD 카드 없음</string>
    <string name="download_no_sdcard_dlg_msg" >파일을 다운로드하기 위해서는 USB 저장소가 필요합니다.</string>
    <string name="download_sdcard_busy_dlg_title">USB 저장소 사용할 수 없음</string>
    <string name="download_sdcard_busy_dlg_msg" >저장소가 사용중입니다. 다운로드를 하려면 USB 저장소를 끄세요.</string>
    <string name="incognito_cookies">사생활 보호 모드에서 쿠키 사용</string>
    <string name="title_flash">Adobe Flash</string>
    <string name="action_manual">수동</string>
    <string name="action_auto">자동</string>
    <string name="action_follow_me">개발자에게 연락하기</string>
    <string name="url_twitter">twitter.com/RestainoAnthony</string>
    <string name="clear_cache">캐시 지우기</string>
    <string name="message_cache_cleared">캐시를 지웠습니다</string>
    <string name="message_import">즐겨찾기를 가져왔습니다</string>
    <string name="message_clear_history">기록을 지웠습니다</string>
    <string name="message_cookies_cleared">쿠키를 지웠습니다</string>
    <string name="max_tabs">최대 탭 수에 도달했습니다</string>
    <string name="message_text_copied">텍스트가 클립보드로 복사되었습니다</string>
    <string name="message_link_copied">링크가 클립보드로 복사되었습니다</string>
    <string name="custom_url">임의의 URL</string>
    <string name="message_blocked_local">로컬 파일 불러오기가 차단되었습니다</string>
    <string name="licenses">오픈 소스 라이센스</string>
    <string name="suggestion">다음을 검색</string>
    <string name="block_ads">광고 차단</string>
    <string name="message_untrusted_certificate">이 웹사이트의 인증서는 신뢰할 수 없습니다. 계속할까요?</string>
    <string name="title_form_resubmission">양식 다시 제출</string>
    <string name="message_form_resubmission">다시 전송할까요?</string>
    <string name="message_location">\n 이(가) 위치를 사용하고자 합니다</string>
    <string name="action_allow">허용</string>
    <string name="action_dont_allow">거부</string>
    <string name="title_sign_in">로그인</string>
    <string name="hint_username">사용자 이름</string>
    <string name="hint_password">암호</string>
    <string name="google_suggestions">검색 제안</string>
    <string name="powered_by_google">Google이 제공함</string>
    <string name="title_adblock">AdBlock</string>
    <string name="message_adblock">AdBlock은 유료 버전인 Lightning Browser+에서 사용할 수 있습니다. Google Play에서 다운로드할 수 있습니다.</string>
    <string name="enable_orbot">Orbot 사용</string>
    <string name="use_tor_prompt">Orbot이 설치되어 있습니다. Tor를 사용할까요?</string>
    <string name="install_orbot">Tor를 사용하려면 Orbot을 설치하세요.</string>
    <string name="yes">예</string>
    <string name="no">아니오</string>
    <string name="clear_cookies_exit">종료할 때 쿠키 지우기</string>
    <string name="clear_history_exit">종료할 때 기록 지우기</string>
    <string name="folder_default">기본값</string>
    <string name="folder_custom">임의의 위치</string>
    <string name="untitled">제목 없음</string>
    <string name="mpl_license">Mozilla Public License v. 2.0</string>
    <string name="freeware">Freeware</string>
    <string name="android_open_source_project">Android Open Source Project</string>
    <string name="hphosts_ad_server_list">hpHosts Ad Server List</string>
    <string name="deleted_tab">다시 열어놓은 기존의 탭</string>
    <string name="rendering_mode">렌더링 모드</string>
    <string name="name_inverted">반전</string>
    <string name="name_grayscale">그레이스케일</string>
    <string name="name_inverted_grayscale">반전된 그레이스케일</string>
    <string name="name_normal">보통</string>
    <string name="sync_history">Google과 기록 동기화</string>
    <string name="title_file_chooser">파일 선택기</string>
    <string name="library_netcipher">NetCipher</string>
    <string name="license_gnu">GNU Lesser General Public License</string>
    <string name="export_bookmarks">즐겨찾기를 백업으로 내보내기</string>
    <string name="import_backup">즐겨찾기를 백업으로부터 가져오기</string>
    <string name="bookmark_export_path">즐겨찾기를 다음으로 내보내기</string>
    <string name="bookmark_settings">즐겨찾기 설정</string>
    <string name="import_bookmark_error">파일로부터 즐겨찾기를 가져올 수 없습니다</string>
    <string name="title_chooser">파일 선택</string>
    <string name="settings_general">일반 설정</string>
    <string name="settings_display">디스플레이 설정</string>
    <string name="settings_privacy">사생활 설정</string>
    <string name="settings_about">라이트닝에 대해서</string>
    <string name="settings_about_explain">버전, 개발자, 라이센스에 대한 정보</string>
    <string name="close_tab">탭 닫기</string>
    <string name="close_all_tabs">모든 탭 닫기</string>
    <string name="third_party">제3자 쿠키 차단</string>
    <string name="available_lollipop">이 기능은 Android 5.0 이상에서 사용할 수 있습니다</string>
    <string name="color_mode">색상 모드 사용</string>
    <string name="reading_mode">리더 모드</string>
    <string name="loading">불러오는 중&#8230;</string>
    <string name="loading_failed">페이지로부터 아무것도 불러올 수 없습니다.</string>
    <string name="snacktory">Snacktory</string>
    <string name="jsoup">jsoup: Java HTML Parser</string>
    <string name="mit_license">MIT License</string>
    <string name="url_contents">URL 상자에 표시할 내용</string>
    <string-array name="url_content_array">
        <item >도메인 (기본값)</item>
        <item >URL</item>
        <item >페이지 제목</item>
    </string-array>
        <string name="invert_color">색상 반전</string>
        <string name="dark_theme">어두운 테마 사용</string>
        <string name="change_after_restart">테마 변경 사항은 브라우저를 재시작해야 적용됩니다.</string>
        <string name="tabs">탭</string>
    </resources>

**Comment by anthonycr** [comment]
Added
