### ISSUE TITLE
Please remove x-wap-profile header, which is dangerous for Tor/Orbot

### ISSUE THREAD

**Issue by chaos095** [anthonycr/Lightning-Browser#252]
With every request, Lightning-Browser sends an x-wap-profile header, which includes a URL.
People using rare phones (such as myself) are probably identified uniquely, also and in particular if they use Tor/Orbot.

**Comment by anthonycr** [comment]
Added support to block this header in https://github.com/anthonycr/Lightning-Browser/commit/7a0c79d11ee1f0a19ebf61b37b8ebd53eee6eb57

Will be in the next release.
