### ISSUE TITLE
For WebChromeClient.onShowFileChooser() in API 21

### ISSUE THREAD

**Issue by mthli** [anthonycr/Lightning-Browser#253]
As we know that in **API 21** Android use new method `WebChromeClient.onShowFileChooser()` to upload file(s) in `WebView`.

But in [Lightning-Browser's source code](https://github.com/anthonycr/Lightning-Browser/blob/master/app/src/main/java/acr/browser/lightning/activity/BrowserActivity.java#L2182) I think the usage of this method is **wrong**. The source code shows that we pick some pictures from the file chooser, in fact the implement is copied from [chromium-webview-samples](https://github.com/GoogleChrome/chromium-webview-samples).

I think the `WebChromeClient.onShowFileChooser()` should **not only** pick some pictures **but also** choose other files such as ".docx" and so on.

To achieve above goal we can implement this method easily, just follow this code(used in `BrowserActivity.java`):

```
private ValueCallback<Uri[]> filePathCallback = null;

@Override
public void showFileChooser(ValueCallback<Uri[]> filePathCallback, WebChromeClient.FileChooserParams fileChooserParams) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        this.filePathCallback = filePathCallback;

        try {
            Intent intent = fileChooserParams.createIntent();
            startActivityForResult(intent, YOUR_REQUEST_CODE);
        } catch (Exception e) {
            // TODO: when open file chooser failed
        }
    }
}

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
    if (requestCode == YOUR_REQUEST_CODE && Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        filePathCallback.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(resultCode, intent));
        filePathCallback = null;
    }
}
```

Hope can help you :)

**Comment by leonghui** [comment]
+1

**Comment by mlensi** [comment]
Noice.  Worked great for me.

**Comment by Ajayappnweb** [comment]
Why this issue still open
