### ISSUE TITLE
Small issue about the keyboard

### ISSUE THREAD

**Issue by Sherlock1995** [anthonycr/Lightning-Browser#259]
Like you can see on these screenshots I have a little problem with the keyboard ( motorola moto g whith lollipop ). When I use the facebook messenger on this browser the keyboard cover the label for the text when I tap on it ( in google chrome all is ok ) like you can see on the second screen.

(thanks you very much for the best mobile browser that I ever try :) )

![1435910905761](https://cloud.githubusercontent.com/assets/12086519/8495167/ac98810c-216b-11e5-9e19-48ac5609e207.jpg)
![1435910937140](https://cloud.githubusercontent.com/assets/12086519/8495168/ac9dbb36-216b-11e5-996e-9aeb68d44d9f.jpg)

**Comment by ecstasybread** [comment]
This only happens when "Hide status bar while browsing" is used by the way.

Seems to be an Android problem with fullscreen mode and listview. See http://stackoverflow.com/a/4789886

**Comment by Sherlock1995** [comment]
thanks for the answer, I solved it :)

**Comment by anthonycr** [comment]
@Sherlock1995 should I close this issue or should we leave it open as it is a bug in Android?

**Comment by Sherlock1995** [comment]
@anthonycr I think you can close this because the bug is already reported as @ecstasybread wrote
