### ISSUE TITLE
bookmarks page, odd column behaviour

### ISSUE THREAD

**Issue by moist-turkey** [anthonycr/Lightning-Browser#263]
Bookmarks tend to show as a two or three column grid on my screen size. I've sometimes found the two and three column layout alternating whilst opening new tabs with the bookmarks page set as default. The speed dial also has a tendency to right-align but centers when dragged.

I'm on a 720p device. Could you perhaps add a settings menu with some small tweak options to the beta? The speed dial could do with some basic settings to force the layout to behave as desired (ie. No sideways scroll, always X columns, recache favicons - often have sites display a globe logo on the speed dial but not in the bookmarks list).

All the best

**Comment by moist-turkey** [comment]
Update: 'Use text reflow' enabled causes the back-and -forth between two and three column layout.

**Comment by anthonycr** [comment]
Bookmarks have been updated with changes that should fix this in the latest Lightning+, an update for Lightning free will be rolling out in the near future, so I am closing this. Please reopen if you see the problem persisting.
