### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by penetrance** [anthonycr/Lightning-Browser#266]
Is it possible to disable WebRTC?

**Comment by dontodd** [comment]
I would love to see this option.

**Comment by anthonycr** [comment]
Not sure this is possible in the WebView

**Comment by anthonycr** [comment]
So actually WebRTC is possible in the webview... but... I haven't implemented the proper methods to support WebRTC, so I am closing this as it does not affect the browser right now. If I add WebRTC support, I will add a switch in privacy settings to disable it and even if it is enabled, you will still need to explicitly grant the website permission to access things like mic and camera.

**Comment by karolba** [comment]
@anthonycr WebRTC works for me in Lightning. No audio/video communication, but that privacy issue is there.

![screenshot_2015-08-31-13-29-31](https://cloud.githubusercontent.com/assets/6043048/9577758/65da4b54-4fe4-11e5-849c-9731ea356c60.png)

**Comment by anthonycr** [comment]
@karolba yes, I opened another issue with that specific information.
