### ISSUE TITLE
paste into address bar adds extra whitespace

### ISSUE THREAD

**Issue by rigid** [anthonycr/Lightning-Browser#273]
When pasting into the address bar, an extra whitespace is added in front of the pasted string.
The obvious consequences (triggering a search engine request) forces to manually remove the space which is ultra annoying.
I hope this is easy to fix.

**Comment by anthonycr** [comment]
I'm not able to reproduce this

**Comment by rigid** [comment]
indeed. Various other apps show the same behaviour. It must be an AOSP or CyanogenMod issue.
Sorry for wasting your time... :angel:
closing issue.
