### ISSUE TITLE
Upload newest version to F-Droid

### ISSUE THREAD

**Issue by l3d00m** [anthonycr/Lightning-Browser#279]
Newest version on playstore is 4.1.1a while F-Droid only has the 4.0.10a. Can you submit the newest version to F-Droid?

**Comment by alanthehat** [comment]
Also, size of apk has jumped from 760KB to 3.2MB between v4.0.2a & v4.0.10a

**Comment by anthonycr** [comment]
Sounds like proguard isn't being run on the APK, it should be around 1.9 MB.

**Comment by l3d00m** [comment]
Will the newest version be uploaded?

**Comment by anthonycr** [comment]
APK size has been increasing because a few libraries have needed to be added to the app, particularly support for the I2P Network has been added (this added a few hundred kb), and Google's support libraries have also increased in size. I've also added in the TwoWayView library for upcoming tab UI as well as another google support library for material design.

**Comment by anthonycr** [comment]
F-Droid builds the APK from the repo, I do not upload any versions as they want to guarantee that the binary matches with the code. Once I merge the latest changes from the dev branch to the master branch it will be built and the latest version will be available on F-droid. I will be merging to master when I next put a release on the Play Store which hopefully will be soon.

**Comment by l3d00m** [comment]
Thank you for the information, I wasn't aware of that.  
Yeah I know that it's basically the pro version. I've also bought the pro version on gplay, but I always prefer F-droid over gplay.

**Comment by alanthehat** [comment]
Thank you for the clarification. I understand why the size is increasing (apart from F-Droid's extra), but I am still disappointed as everything else is also increasing in size yet it all has to fit on the same phone I had last month :-(

**Comment by fbis251** [comment]
Any updates on this?

**Comment by anthonycr** [comment]
@fbis251 there is currently a version in beta, when it moves to production I will merge dev into master and then the f-droid version will be updated

**Comment by l3d00m** [comment]
nice, thank you

**Comment by l3d00m** [comment]
Can you now upload it to F-droid?

**Comment by anthonycr** [comment]
Newest version is now on F-droid: https://f-droid.org/repository/browse/?fdfilter=lightning&fdid=acr.browser.lightning 

Note: F-droid builds the APK and signs it themselves, so I am not responsible for uploading the APK so that it is guaranteed to be built from open source code.
