### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by strangecoder** [anthonycr/Lightning-Browser#291]
Above error on syncing gradle.

**Comment by anthonycr** [comment]
What branch is this on? The travis CI builds are passing and I have no such gradle problems so this is a problem with your build environment. [You likely have not pulled down the netcipher library.](http://stackoverflow.com/questions/22743582/error-configuration-with-name-default-not-found-in-android-studio). Please follow the instructions in the README.md about how to sync this library.
