### ISSUE TITLE
[SECURITY] No SSL validation at all

### ISSUE THREAD

**Issue by untitaker** [anthonycr/Lightning-Browser#297]
Lightning Browser, as installed from F-Droid, does not verify anything about the SSL certificate in any way.

https://badssl.com/ <= Most bad certificates presented on this site are silently accepted.

**Comment by kuc** [comment]
Bug is in `LightningView#onReceivedSslError()`

Only `SslError.SSL_UNTRUSTED` is alerted to user, other errors are silently ignored.
Easy fix, I'm starting working on this.

**Comment by kuc** [comment]
Done.
