### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by obifur** [anthonycr/Lightning-Browser#300]
update:
This issue relates to the Play Store version - the F-Droid version (4.0.10a) works for me. Normally it crashs immediatly, but sometimes, especially if I start lightning through the Play Store, it starts. Then it crashes when I try to visit another url.
Device: Toshiba AT300se, Tablet, Android 4.1.1

### Logcat, filtered for "arc.browser":

10-02 07:14:05.676   302   690 I ActivityManager: START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=acr.browser.barebones/acr.browser.lightning.activity.MainActivity u=0} from pid 598

10-02 07:14:05.836   302   312 I ActivityManager: Start proc acr.browser.barebones for activity acr.browser.barebones/acr.browser.lightning.activity.MainActivity: pid=1806 uid=10190 gids={3003, 1015, 1028}

10-02 07:14:06.096  1806  1806 I dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method acr.browser.lightning.activity.BrowserActivity.s

10-02 07:14:06.476  1806  1806 I dalvikvm: Could not find method android.widget.TextView.setTextAppearance, referenced from method acr.browser.lightning.activity.w.a

10-02 07:14:06.476  1806  1806 I dalvikvm: Could not find method android.widget.TextView.setTextAppearance, referenced from method acr.browser.lightning.activity.w.a

10-02 07:14:06.546  1806  1806 I dalvikvm: Could not find method android.webkit.WebSettings.setMediaPlaybackRequiresUserGesture, referenced from method acr.browser.lightning.view.LightningView.<init>

10-02 07:14:06.546  1806  1806 I dalvikvm: Could not find method android.webkit.WebSettings.setMixedContentMode, referenced from method acr.browser.lightning.view.LightningView.<init>

10-02 07:14:06.546  1806  1806 I dalvikvm: Could not find method android.webkit.WebSettings.setMixedContentMode, referenced from method acr.browser.lightning.view.LightningView.<init>

10-02 07:14:06.546  1806  1806 I dalvikvm: Could not find method android.webkit.WebSettings.getDefaultUserAgent, referenced from method acr.browser.lightning.view.LightningView.a

10-02 07:14:06.546  1806  1806 I dalvikvm: Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method acr.browser.lightning.view.LightningView.a

10-02 07:14:06.796  1806  1806 I dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method acr.browser.lightning.j.c.b

10-02 07:14:06.826  1806  1806 I dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method acr.browser.lightning.j.c.a

10-02 07:14:06.826  1806  1806 I dalvikvm: Could not find method android.app.Activity.requestPermissions, referenced from method acr.browser.lightning.j.c.a

10-02 07:14:06.826  1806  1806 I dalvikvm: Could not find method android.webkit.WebView.evaluateJavascript, referenced from method acr.browser.lightning.view.f.onPageFinished

10-02 07:14:06.826  1806  1806 I dalvikvm: Could not find method android.webkit.WebResourceRequest.getUrl, referenced from method acr.browser.lightning.view.f.shouldInterceptRequest

10-02 07:14:06.826  1806  1806 I dalvikvm: Could not find method android.webkit.WebViewClient.shouldInterceptRequest, referenced from method acr.browser.lightning.view.f.shouldInterceptRequest

10-02 07:14:07.676   302   345 I ActivityManager: Displayed acr.browser.barebones/acr.browser.lightning.activity.MainActivity: +1s850ms

10-02 07:14:08.246   105   105 I DEBUG   : pid: 1806, tid: 1806, name: owser.barebones  >>> acr.browser.barebones <<<

10-02 07:14:09.096   302   690 I WindowState: WIN DEATH: Window{41cfb930 acr.browser.barebones/acr.browser.lghtning.activity.MainActivity paused=false}

10-02 07:14:09.096   302   312 I ActivityManager: Process acr.browser.barebones (pid 1806) has died.

10-02 07:14:09.136   302   312 W ActivityManager: Force removing ActivityRecord{41c999f8 acr.browser.barebones/acr.browser.lightning.activity.MainActivity}: app died, no saved state

### Logcat filtered for "warnings":

10-03 11:49:44.412 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10168: Landroid/view/Window;.setStatusBarColor (I)V

10-03 11:49:44.442 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 1309: Landroid/app/Activity;.finishAfterTransition ()V

10-03 11:49:44.462 13401 13401 W dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)

10-03 11:49:44.462 13401 13401 W dalvikvm: VFY: unable to resolve interface method 10152: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z

10-03 11:49:44.462 13401 13401 W dalvikvm: VFY: unable to resolve interface method 10156: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;

10-03 11:49:44.532 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10077: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V

10-03 11:49:44.542 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 1413: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;

10-03 11:49:44.542 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 1410: Landroid/content/Context;.getColor (I)I

10-03 11:49:44.592 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10859: Landroid/widget/TextView;.setTextAppearance (I)V

10-03 11:49:44.592 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10859: Landroid/widget/TextView;.setTextAppearance (I)V

10-03 11:49:44.612 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 1525: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;

10-03 11:49:44.612 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 1527: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;

10-03 11:49:44.632 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10339: Landroid/webkit/WebSettings;.setMediaPlaybackRequiresUserGesture (Z)V

10-03 11:49:44.632 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10340: Landroid/webkit/WebSettings;.setMixedContentMode (I)V

10-03 11:49:44.632 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10340: Landroid/webkit/WebSettings;.setMixedContentMode (I)V

10-03 11:49:44.632 13401 13401 W dalvikvm: VFY: unable to resolve static method 10315: Landroid/webkit/WebSettings;.getDefaultUserAgent (Landroid/content/Context;)Ljava/lang/String;

10-03 11:49:44.632 13401 13401 W dalvikvm: VFY: unable to resolve static field 4129 (TEXT_AUTOSIZING) in Landroid/webkit/WebSettings$LayoutAlgorithm;

10-03 11:49:44.632 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10291: Landroid/webkit/CookieManager;.setAcceptThirdPartyCookies (Landroid/webkit/WebView;Z)V

10-03 11:49:44.682 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 1305: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I

10-03 11:49:44.682 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 1305: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I

10-03 11:49:44.682 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 1329: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V

10-03 11:49:44.682 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10362: Landroid/webkit/WebView;.evaluateJavascript (Ljava/lang/String;Landroid/webkit/ValueCallback;)V

10-03 11:49:44.692 13401 13401 W dalvikvm: VFY: unable to find class referenced in signature (Landroid/webkit/WebResourceRequest;)

10-03 11:49:44.692 13401 13401 W dalvikvm: VFY: unable to resolve interface method 10313: Landroid/webkit/WebResourceRequest;.getUrl ()Landroid/net/Uri;

10-03 11:49:44.702 13401 13401 W dalvikvm: VFY: unable to resolve virtual method 10409: Landroid/webkit/WebViewClient;.shouldInterceptRequest (Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;)Landroid/webkit/WebResourceResponse;

10-03 11:49:44.732 13401 13401 E dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method c.a.a.b.a.a

10-03 11:49:44.732 13401 13401 W dalvikvm: VFY: unable to resolve check-cast 1313 (Landroid/util/ArrayMap;) in Lc/a/a/b/a;

10-03 11:49:44.732 13401 13401 E dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method c.a.a.b.a.b

10-03 11:49:44.732 13401 13401 W dalvikvm: VFY: unable to resolve check-cast 1313 (Landroid/util/ArrayMap;) in Lc/a/a/b/a;

10-03 11:49:44.842 13401 13401 W dalvikvm: VFY: unable to resolve static method 1962: Landroid/os/Trace;.endSection ()V

10-03 11:49:44.842 13401 13401 W dalvikvm: VFY: unable to resolve static method 1961: Landroid/os/Trace;.beginSection (Ljava/lang/String;)V

10-03 11:49:44.852 13401 13401 E RecyclerView: No adapter attached; skipping layout

10-03 11:49:44.952 13401 13401 E RecyclerView: No adapter attached; skipping layout

10-03 11:49:46.652 13401 13401 E RecyclerView: No adapter attached; skipping layout

10-03 11:49:48.822 13401 13401 W IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection

10-03 11:49:48.842 13401 13401 W IInputConnectionWrapper: clearMetaKeyStates on inactive InputConnection

10-03 11:49:48.962 13401 13401 W IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection

10-03 11:49:48.992 13401 13401 W IInputConnectionWrapper: clearMetaKeyStates on inactive InputConnection

10-03 11:49:49.082 13401 13401 E RecyclerView: No adapter attached; skipping layout

10-03 11:49:49.882 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114949:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:49.882 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114949:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:49.892 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114949:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.052 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.052 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.052 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.062 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.062 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.062 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.062 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.122 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.122 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.132 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.132 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.142 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.142 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.142 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.202 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.202 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.202 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.202 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.202 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.252 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.272 13401 13401 F libc    : Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 13401 (owser.barebones)

10-03 11:49:50.372 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.372 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.372 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.772 13401 13434 W chromium: external/chromium/net/disk_cache/backend_impl.cc:1829: [1003/114950:WARNING:backend_impl.cc(1829)] Destroying invalid entry.

10-03 11:49:50.792   304   689 W ActivityManager: Force removing ActivityRecord{41bf40c0 acr.browser.barebones/acr.browser.lightning.activity.MainActivity}: app died, no saved state

10-03 11:49:50.852   304   314 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 13401 uid 10190

10-03 11:49:57.212   304   568 W ThrottleService: unable to find stats for iface rmnet0

**Comment by anthonycr** [comment]
This looks like a WebView bug ```libc : Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 13401 (owser.barebones)``` causing the crash which I don't think I can fix. However, there also looks like another bug in there which I will look into.

**Comment by obifur** [comment]
The F-Droid Version is now updated to 4.3.2a and it works for me! So this issue only effects the Play Store version.

**Comment by anthonycr** [comment]
that's great! But the play store version uses the exact same code, so this was likely a corrupt browser cache which I can't do anything about. If this happens again try clearing the cache and it should fix it.

I'm going to close this issue as it's a WebView bug that I can't fix.
