### ISSUE TITLE
Remove X-Requested-With header in each request

### ISSUE THREAD

**Issue by iampradip** [anthonycr/Lightning-Browser#317]
WebView sends this header with app package name with it by default. Please remove it.

Ref:

1) https://stackoverflow.com/questions/17832313/android-disable-x-requested-with-header-in-webview

2) https://stackoverflow.com/questions/19720059/how-to-modify-the-value-of-the-key-x-requested-with-in-the-request-headers-of

3) https://github.com/javalite/activeweb/issues/211

**Comment by anthonycr** [comment]
It seems to be working using the load with headers method, I need to test to see if there are any problems with it or not. Documentation suggests that it adds the specific header to the request, but usage is indicating that the header is in fact overridden completely which is good news.

I played around with this a while ago but for some reason I didn't use it, if it continues to work as desired I will be able to fix https://github.com/anthonycr/Lightning-Browser/issues/252 as well, and also allow the do not track header to be sent optionally.

**Comment by anthonycr** [comment]
Added support to remove this identifying header in https://github.com/anthonycr/Lightning-Browser/commit/7a0c79d11ee1f0a19ebf61b37b8ebd53eee6eb57

Will be in the next release.

**Comment by iampradip** [comment]
Header is removed in page request, but it's not removed in css/js/xhr etc requests. Here's test page: http://headerscheck.byethost24.com/headers.php

**Comment by moziqi** [comment]
please，help me ，我不会弄

**Comment by glzlaohuai** [comment]
It only remves the 'x-request-with' header in the initial request, the sequent ones still contains the header.

**Comment by iampradip** [comment]
> 
> 
> It only remves the 'x-request-with' header in the initial request, the sequent ones still contains the header.

My pull request removes header in all requests but I would rather suggest to use Firefox or some other browser which has its own rendering engine instead of relying on any internal or WebView based browser.
