### ISSUE TITLE
can't figure out how to use the command''git submodule update --init --recursive''

### ISSUE THREAD

**Issue by kurdoxxx** [anthonycr/Lightning-Browser#320]
as the title says.. i cant fiure it out, i also posted this issue on the thunderbrowser...

**Comment by kuc** [comment]
What OS are you using?

**Comment by kurdoxxx** [comment]
I'm using Windows 10

**Comment by kuc** [comment]
And [Git for Windows](https://git-for-windows.github.io/)?

Open folder with local repo, right click in empty space -> "Open Git Bash here"
Type `git submodule update --init --recursive` and ENTER.

**Comment by kurdoxxx** [comment]
how to open a folder with local repo?, im really new to git

**Comment by kuc** [comment]
Where are you cloned this repo to your computer? Open this folder in Explorer.

**Comment by kuc** [comment]
Read this: https://guides.github.com/activities/contributing-to-open-source/

**Comment by anthonycr** [comment]
Try reading this http://www.vogella.com/tutorials/Git/article.html#submodules

I'm going to close this as it's not an issue with the project.
