### ISSUE TITLE
cannot upload files

### ISSUE THREAD

**Issue by lombartz** [anthonycr/Lightning-Browser#339]
Tested on XDA with CM11:  when pressing the select file button in the manage attachments tab nothing happens. Opera works.

**Comment by JonasCz** [comment]
Clicking the "attach files by selecting them" below while writing this comment brings up the chooser dialog for me, both on android 4.2, as well as CM 11. Maybe it's something wrong with XDA ? (don't have an account, so can't try)

**Comment by lombartz** [comment]
Hmm, error came with the latest build and i tested it several times. Didn't work even here. I restored the previous build and it worked again. Now it also works with newest build after updating again. Don't know why but seems issue was temporary ...
--

M.Wersig


Am 1. Dezember 2015 15:55:25 MEZ, schrieb JonasCz <notifications@github.com>:
