### ISSUE TITLE
let's encrypt certificate not trusted

### ISSUE THREAD

**Issue by christianfl** [anthonycr/Lightning-Browser#352]
Whenever I want to visit my own web page which has a certificate from let's encrypt, Lightning says: 

Connection to this site is not secure: - certificate is not trusted. Proceed anyway?

Could you import the let's encrypt certificate?

**Comment by kuc** [comment]
Lightning Browser is using system trust store, so you must do it yourself in device settings.

**Comment by christianfl** [comment]
Thanks, I already thought about that but the Let's Encrypt was already in the trust store. However, it is working fine now. Maybe it had something to do with a wrong server config.
