### ISSUE TITLE
[Feature request] Share link by long pressing it

### ISSUE THREAD

**Issue by JonasCz** [anthonycr/Lightning-Browser#353]
It would be cool if there was an option to share a link when long pressing it. Currently, the dialog that comes up when long pressing on a link has three buttons: Copy URL, Open, and New Tab. 

Maybe that dialog could get a button to share the URL (maybe instead of the "copy URL" one ?), or maybe replace it with a list of choices, like Firefox.

**Comment by anthonycr** [comment]
Fixed by https://github.com/anthonycr/Lightning-Browser/commit/b0d07298ddf4baad381e904b6f739f275b4a90f9
