### ISSUE TITLE
Lightning Tries to Download Certain apk File as txt File

### ISSUE THREAD

**Issue by LibertatisPrius** [anthonycr/Lightning-Browser#357]
Trying to download the Piwik Mobile 2 apk (http://piwik.org/wp-content/uploads/2014/12/PiwikMobile2.2forAndroid.apk) with Lightning opens a new tab and asks if you want to save "PiwikMobile2.txt". Selecting Download opens a new tab which repeats the process. I have not been able to reproduce this error with other apk files.

This may be an error on Piwik's part, but Firefox downloaded the apk just fine.

Lightning version: 4.2.3a

**Comment by kuc** [comment]
```
HEAD http://piwik.org/wp-content/uploads/2014/12/PiwikMobile2.2forAndroid.apk

Accept-Ranges: bytes
Cache-Control: max-age=691200
Content-Length: 10183025
Content-Type: text/plain
Date: Sat, 12 Dec 2015 14:19:20 GMT
Etag: "30f62b5b-9b6171-50abf578885ac"
Expires: Sun, 20 Dec 2015 14:19:20 GMT
Last-Modified: Sun, 21 Dec 2014 19:56:47 GMT
Server: Apache/2.2
```

It's not a bug in browser, it's server fault:
`Content-Type: text/plain`


> Firefox downloaded the apk just fine.

Some browsers implement content sniffing: https://en.wikipedia.org/wiki/Content_sniffing
