### ISSUE TITLE
Can't install latest version (4.3.3)

### ISSUE THREAD

**Issue by Mr5quid** [anthonycr/Lightning-Browser#416]
Hi,

I saw that an update for Lightning 4.3.3 was available on F-Droid so I tried to upgrade but apparently the package was signed with a different key so I had to uninstall the one I had, which in itself is a little bit annoying since that means losing all my bookmarks and so on. But the main issue is that I can't install the latest version. I grabbed some logs for you : http://pastebin.com/3m0PeJhv

Does this version fix the downloading issue for Marshmallow ? I really love your browser it's truly amazing but I have to juggle with two browsers whenever I need to download a file.

Thanks a lot for your good work, keep it up, and I hope you fix this issue too so that I can go back to using Lightning :).

**Comment by TGuptaNYC** [comment]
I recommend you download from the release page on Github itself.

**Comment by Mr5quid** [comment]
Thanks for the tip. I indeed remembered that in an attempt to fix the downloading issue for Marshmallow I installed Lightning from the apk given from here, hoping that it was a different version. That's why F-Droid told me the signing key was different. It is unclear why I could not install the latest version from F-Droid though, but reinstalling the app with the latest apk worked.
