### ISSUE TITLE
Links cannot be opened correctly

### ISSUE THREAD

**Issue by leonlywong** [anthonycr/Lightning-Browser#417]
After 4.3.3 update, whenever opening links from other apps, the browser shows the home page instead of the website.
Only happens when choosing not to restore losts tab on start.
Thanks!

**Comment by Roboe** [comment]
Exact same issue here

**Comment by revuwa** [comment]
Yup, I have the same issue (on my Samsung i9300 @ AOSP 6.0.1).
Thanks @leonlywong for the 'restore lost tabs on start'-relationship hint.

It also works, if I open the link from the external app the second time, but it really seems to be a bug.

**Comment by sbruder** [comment]
At me the bug appears ever when I closed Lightning over "Close all tabs" and no tab is open before I opened the link.

**Comment by haverholm** [comment]
Ditto on the Nexus 5X running PureNexus rom. For someone who routinely closes all recent apps, opening on a blank tab is a bit of a bother.

**Comment by anthonycr** [comment]
Closing as fixed
