### ISSUE TITLE
Updating to 4.3.3 (fdroid) loses all open tabs

### ISSUE THREAD

**Issue by Bubu** [anthonycr/Lightning-Browser#421]
Today I updated Lightning from 4.2.3a to 4.3.3 through fdroid. After the update there were no more open tabs (before: 10). I had to find them all in the history page and restore them manually.

Is that intentional/ a known problem or a bug in the upgrade process?

**Comment by chk1** [comment]
Same happened to me on Google Play. I restored 4.2.3a via Titanium Backup (just app, no data) and tabs were restored.

**Comment by Bubu** [comment]
This happened again to me, this time unrelated to an upgrade, just after closing the browser and reopening it.

Lightning was somewhat unresponsive before, that's why I closed it.
In any case I reopened all tabs from history.

**Comment by Bubu** [comment]
This seems fixed in 4.4.1. Haven't had a freeze since then.
