### ISSUE TITLE
Feature request: custom DNS

### ISSUE THREAD

**Issue by virtualdj** [anthonycr/Lightning-Browser#446]
Do you think it would be possible to implement DNS resolution using **dnsjava** library to allow using a custom DNS (such as Google DNS **8.8.8.8**) for example to avoid Internet Provider filtering?
Or is this something that's handled at low level? I was unable to find any web browser capable of using a custom DNS.

**Comment by kuc** [comment]
I think it's hardly possible, because Lightning is just a GUI for [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview), which does all networking.

But you can set a proxy, so you could install proxy that allows you to use custom DNS server, eg.: [ProxyDroid](https://play.google.com/store/apps/details?id=org.proxydroid)

>** FEATURES **
>(...)
>9. DNS proxy for guys behind the firewall that disallows to resolve external addresses

**Comment by razorshiv** [comment]
There are better and more efficient ways to resolve dns. No sense in reinventing the wheel. You can use a proxy such as TOR, vpn such as PIA and if rooted there are several apps both on play and fdroid that can modify the dns settings of the android os. The fact that you were unable to find a browser capable of custom dns resolution is very telling in itself. It's just easier to do it at "low level" as you instinctively mentioned.

Regards

**Comment by virtualdj** [comment]
> You can use a proxy such as TOR, vpn such as PIA
Of course, but I was looking for a more "softer" approch as switching DNS on the router is normally enough; however the same is not possible using a 3G connection if you're not rooted.
I'll try with the proxy solution, then.

**Comment by kn00tcn** [comment]
i thought android has standard vpn settings for several versions now, you would want some kind of virtual vpn app that does dns, if that's even possible... there are firewall or adblocking apps that use this method, they're just a localhost vpn

**Comment by virtualdj** [comment]
> there are firewall or adblocking apps that use this method
Yes but either they don't work or they require root.
Basically the blocked addresses are reachable by IP, but the provider DNS Server just diverts you to another (wrong) server.

**Comment by kn00tcn** [comment]
they should work, i tried one or two from fdroid, i dont recall entering root but not sure
