### ISSUE TITLE
Opening links from other apps does not work

### ISSUE THREAD

**Issue by insintesi** [anthonycr/Lightning-Browser#450]
Hi,

First things first, I loved the app so much I bought the paid version instantly!
Now, with the latest release, whenever I open a link elsewhere and Lightning opens up as the default browser, it opens the default page but not the actual link. I have to return to the app and tap on the link once again. Then, a second tab with the requested link is opened.

I use Lightning+ on an Android 6.0.1. If you need more information, I’ll gladly provide it.

Thanks in advance!

**Comment by razorshiv** [comment]
This has to do with the setting "Restore lost tabs on start" which is in the advanced menu. If disabled and unchecked, no external links will work. Not from inside another application or even a bookmark on the home screen. You will be taken to the default home page every time. To correct this behavior, the setting MUST be left enabled and checked. However, this defeats the purpose of the setting completely.

To combat this issue, leave the setting enabled and checked. But when you want to close the app and all tabs, long press the back button which will reveal the "Close all tabs" ;menu thus emptying the tabs until the next session. A pain, but gets the desired results.

This is a duplicate issue as I have already created one previously.
https://github.com/anthonycr/Lightning-Browser/issues/443

Regards

**Comment by insintesi** [comment]
Ah, I see! I actually like this solution, I wasn’t aware of the back button function. Thank you very much for your help!

**Comment by razorshiv** [comment]
Looks like this was fixed in this commit. We are waiting for a merge.
#439

Regards
