### ISSUE TITLE
Quick switching to desktop mode

### ISSUE THREAD

**Issue by LuccoJ** [anthonycr/Lightning-Browser#453]
Increasingly many websites offer crippled functionality in their "mobile" mode,  presumably to push their dedicated apps, and so it becomes necessary to view them in "desktop" mode. This can be achieved in Lightning  by going to the general settings and changing the user agent.

However, this method is slow, requires manually refreshing the opened page, and applies to all sites globally until one switches back. Other browsers offer a "View in desktop mode"-type toggle within easy reach from inside a page view, and I would like Lightning to provide a similar feature.

I think it would be even better if the setting were remembered for individual websites and bookmarks.

**Comment by FallenKN** [comment]
Swipe from the right and click the Desktop Icon on the left bottom

**Comment by LuccoJ** [comment]
Oh, whoops. Somehow I thought that was related to bookmarks...

**Comment by LuccoJ** [comment]
Oh, whoops. Somehow I thought that was related to bookmarks...

**Comment by kn00tcn** [comment]
that's a bit of a crude assumption, which sites are they?

proper responsive design doesnt hide useful things, the purpose is to scale from 320 to 1920 width & beyond

i most certainly do not enjoy having to zoom in on desktop mode & constantly scrolling left & right just to read a paragraph

the desktop toggle doesnt appear to do anything on anandtech, which means to fully realize the goal of desktop mode, the browser still needs to fake its viewport width to 1024 or 1280, not just the useragent

an alternate reason for actual separate mobile/desktop versions of a site is to reduce the bandwidth & cpu load for mobile visitors, or maybe even things like desktop using flash to play video

**Comment by LuccoJ** [comment]
"Assumption"?
My issue, even if it had resulted from blatantly overlooking a button, was filed due to very practical problems I was experiencing, not arbitrary assumptions.

I don't think it's in scope here to discuss individual websites' design choices in detail, but off the top of my head (I'm sure I've encountered more, but these I've recently had problems with):

* youtube.com doesn't let you upload files in mobile mode
* tripadvisor.com very insistently nags you to install the app, and only lets you view the first 3 review of each venue without it
* facebook.com doesn't let you use instant messaging and prompts you to install the app instead

**Comment by kn00tcn** [comment]
i didnt mean you the user may have overlooked anything, thanks for the list of douchebag sites

i actually do remember a nightmare trying to read about.com on a low end 2012 320x480 device, things constantly popping up, menus not rendering properly, extremely low framerate...

fb at least you can go to the messages page (maybe open in a second tab?) instead of totally locking out communication

**Comment by LuccoJ** [comment]
Facebook will be removing access from the instant messages soon, they are currently warning me that I will need to switch to the app.
