### ISSUE TITLE
Proper validation of https Certificate Subject Alt Name

### ISSUE THREAD

**Issue by jroldroyd** [anthonycr/Lightning-Browser#459]
I have started to see numerous warnings when visiting various different https web sites:

> Warning: Connection to this site is not secure: - domain in certificate does not match the site domain.

Looking at the certificate in firefox, I see I am visiting sites that are hosted at a hosting company.  The certificate has a Certificate Subject Alt Name which contains a list of DNS Names that includes the domain for the "site_I_am_visiting.com", as well as the wildcard "*.site_I_am_visiting.com".  But the actual certificate name is for the hosting company.

An example where you will see this is [https://theguardian.com/](url).

Perhaps the certificate validation code needs updating?  Or a library needs updating?  Or does some flag need to be used to also verify against Subject Alt Name?

**Comment by razorshiv** [comment]
I have an N6P with CM13 August 5 build and latest lightning browser.
The example website you provided resolves without error and does a proper 301 redirect to another secure domain without issue.

In comparison. I have not experienced any of the issues you are suggesting. Sounds like an issue with the sites you are visiting and maybe have to do with shared ssl and or a host header misconfiguration.

I'm guessing here but post some other example sites having issues we can visit to confirm.

Regards

**Comment by jroldroyd** [comment]
Interesting that it is not a problem for you.

Another example for me is [https://m.washingtonpost.com/](url).  Also hosted, also has the "*.washintonpost.com" domain listed in a Subject Alt Name field.

And another is [https://www.wunderground.com/](url).  In this one, the Cert Name is "\*.wunderground.com" and the Subject Alt Name field is also "*.wunderground.com".

My phone is a Samsung S7 Edge, not-rooted, running stock, up-to-date firmware.  I am also seeing the same problem on a Moto X 2015 Pure, also not-rooted, stock, up-to-date.

I do not see the problem when I use the Firefox browser on the phone.

Seeing this on two different vendors' phones and not in Firefox is what led me to conclude that this is a Lightning-specific issue.

Based on your not having this problem on CM13, maybe this is to do with Lightning's use of the stock SSL libraries?  Maybe Firefox uses different SSL libraries?  If that's the case, what does Lightning need to do to avoid this error/warning?

**Comment by jroldroyd** [comment]
Hmm, this may have something to do with the default local network here which has a DNS-based adblocker configuration.

Switching to a different local network with no DNS-based adblocking seems to eliminate the problem.  And, a simple change to the adblock config on the affected network also appears to have eliminated the problem.

Odd however, that on the affected network, it is a problem for Lightning but not for Firefox.

Anyway, sorry for the noise.

**Comment by kn00tcn** [comment]
i would think it's a problem of webview or webkit or the android OS itself

pretty sure FF has its own cert list separated from the OS it runs on (not to mention its own way of handling them)
