### ISSUE TITLE
what's the roadmap for the next 'release'? anything users can do? beta/RC version?

### ISSUE THREAD

**Issue by kn00tcn** [anthonycr/Lightning-Browser#462]
are releases a compilation of all commits up to a point or does there have to be cherry picking due to unfinished changes?

**Comment by craftyguy** [comment]
I'm also interested in hearing about this. There are a lot of open PRs and releases seem to be rather sporadic at best. I don't want to spend time fixing issues, etc only to have my PRs languish.

**Comment by kn00tcn** [comment]
well technically anyone can set up the dev environment & compile their own apk, but gotta alert those fdroid or play users

**Comment by craftyguy** [comment]
I don't know that additional fragmentation of Lightning is the answer I was looking for, but if that's the only answer then, well, ok.

**Comment by kyak** [comment]
It has been a long time since release. I'd love to have all commits from after 4.3.3 release, but it's not possible. The beta program seems dead and setting up development environment just to build Lightning? No, thanks.

**Comment by kuc** [comment]
@kyak Last year I tried to setup uploading auto-releases form Travis: https://github.com/kuc/Lightning-Browser/commit/1d16f8021370e2fc84ed0a522fb94f797fbf2f3f

Cavecats:
- those are `debug` builds, so they include memory leak detector etc.
- APK is signed with debug key, so it's not possible to upgrade without losing all settings and bookmarks

**Comment by kyak** [comment]
@kuc it's not bad! I think i would use these auto-releases if @anthonycr were to set up them.

**Comment by kuc** [comment]
@kyak OK, so maybe I should revive this idea and make PR & instruction for @anthonycr ...

**Comment by kyak** [comment]
@kuc i will definitely upvote this PR!

**Comment by craftyguy** [comment]
@kuc it's not possible to set it up to produce release builds, albeit with a different signature than @anthonycr.. but it would still be useful if we never see any more releases from him!

**Comment by kn00tcn** [comment]
> so it's not possible to upgrade without losing all settings and bookmarks

time for an import/export settings feature, would be useful for multi device users

i havent tried the existing bookmarks import/export feature, export seems to make a normal looking json
