### ISSUE TITLE
v4.4.2 missing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [anthonycr/Lightning-Browser#534]
When I take a look in the playstore I notice, that lightning's current version is v4.4.2. In the F-Droid store the current version is v4.4.1.

What's the reason for the different versions? Is this project still alive?

Kind Regards,

Krawei

**Comment by krihsna** [comment]
@Krawei
be patient & request kindly to upload version 4.4.2 at https://gitlab.com/fdroid/fdroiddata/issues

i am not quite sure about the above repo, please check yourself & then open an issue.

its strange that app author forgot to upload new version on github.

two version of app:
paid version app id: acr.browser.lightning
free version app id: acr.browser.barebones

**Comment by Yowlen** [comment]
I believe this can be closed. 4.4.2 is on F-Droid, though it's apparently marked "unstable", so you'll have to either install it manually or have "Suggest unstable updates" enabled in the settings.

**Comment by Krawei** [comment]
No "version delay" anymore. I'll close this issue.
