### ISSUE TITLE
FeatureRequest: Add keyboard shortcuts

### ISSUE THREAD

**Issue by Massimo-B** [anthonycr/Lightning-Browser#536]
Hi,

Android apps often forget about tablets with hardware keyboard.
I'd like to see some simple shortcuts like CTRL+w to close tabs or CTRL+PageUp/Down for tab switching. Just adapt to some of the common shortcuts of common desktop browsers...
Thank you.

**Comment by Zoraver** [comment]
See pull request #519.

**Comment by anthonycr** [comment]
PR merged, thanks @Zoraver!
