### ISSUE TITLE
Bookmarks in folders are not shown on the (bookmarks) homepage

### ISSUE THREAD

**Issue by jaimet** [anthonycr/Lightning-Browser#585]
I have about 10 bookmarks, half of which are "top-level" (not in a named folder) and the other half of which are in a named folder (set using "Edit bookmark" -> "Folder name"). When I set my homepage to be the bookmarks page, only my top-level bookmarks are shown (there are no folders shown on the "bookmarks" homepage).

(PS: a huge "thank-you" for writing this great browser!)

**Comment by anthonycr** [comment]
Thanks for this report, fixed by https://github.com/anthonycr/Lightning-Browser/commit/12a93d208d7a3d660dd401a2cc37519937e16867
