### ISSUE TITLE
v4.4.3 mussing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [anthonycr/Lightning-Browser#587]
When I take a look in the playstore I notice, that lightning's current version is v4.4.3. In the F-Droid store the current version is v4.4.2. There's no "unstable"-marked version in the F-Droid store so far.

What's the reason for the difference on the versions? Is there a failure in build process?

Kind Regards,

Krawei

**Comment by Roshless** [comment]
Just sent [pull request](https://gitlab.com/fdroid/fdroiddata/merge_requests/2318) for update. For some reason it requires manual update.

**Comment by anthonycr** [comment]
@Krawei the current version should be 4.5.0. I made a mistake when I published 4.4.3 and didn't make a tag so that version wasn't able to be pushed to F-Droid, but 4.5.0 has been properly tagged. I'll close this issue once 4.5.0 is up on the store, and I'll make sure in the future to make a PR on the f-droid data repo 👍

**Comment by razorshiv** [comment]
I'm confused. 4.5.0 is already in the play store. When is 4.5.0 expected to hit the f-droid repo?

**Comment by anthonycr** [comment]
@razorshiv by "store" I'm referring to the F-droid "store." I don't know when 4.5.0 will hit f-droid, the pull request was made a couple days ago for 4.5.0 but I still don't see it up

**Comment by razorshiv** [comment]
@anthonycr Understood. And thank you plus all those who contributed to deliver such an awesome browsing experience.  Keep it simple, privacy minded and lightning fast. :)

**Comment by anthonycr** [comment]
FYI... looks like F-Droid's build server has been failing to deploy a lot of apps (lightning included). You can track the issue here: https://gitlab.com/fdroid/admin/issues/38

**Comment by anthonycr** [comment]
Looks like 4.5.0 is up on the store, closing.
