### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by aaa2103** [anthonycr/Lightning-Browser#627]
> Error:A problem occurred configuring root project 'Lightning-Browser-dev'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download kotlin-gradle-plugin.jar (org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.4-3)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.1.4-3/kotlin-gradle-plugin-1.1.4-3.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.1.4-3/kotlin-gradle-plugin-1.1.4-3.jar'.
            > Connect to akamai.bintray.com:443 [akamai.bintray.com/49.44.100.182] failed: Connection timed out: connect
   > Could not download gson.jar (com.google.code.gson:gson:2.6.2)
      > Could not get resource 'https://jcenter.bintray.com/com/google/code/gson/gson/2.6.2/gson-2.6.2.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/google/code/gson/gson/2.6.2/gson-2.6.2.jar'.
            > Connect to akamai.bintray.com:443 [akamai.bintray.com/49.44.100.182] failed: Connection timed out: connect
   > Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.1.4-3)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.1.4-3/kotlin-stdlib-1.1.4-3.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.1.4-3/kotlin-stdlib-1.1.4-3.jar'.
            > Connect to akamai.bintray.com:443 [akamai.bintray.com/49.44.100.182] failed: Connection timed out: connect
   > Could not download kotlin-android-extensions.jar (org.jetbrains.kotlin:kotlin-android-extensions:1.1.4-3)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-android-extensions/1.1.4-3/kotlin-android-extensions-1.1.4-3.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-android-extensions/1.1.4-3/kotlin-android-extensions-1.1.4-3.jar'.
            > Connect to akamai.bintray.com:443 [akamai.bintray.com/49.44.100.182] failed: Connection timed out: connect
   > Could not download kotlin-compiler-embeddable.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.1.4-3)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.4-3/kotlin-compiler-embeddable-1.1.4-3.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1.4-3/kotlin-compiler-embeddable-1.1.4-3.jar'.
            > Connect to akamai.bintray.com:443 [akamai.bintray.com/49.44.100.182] failed: Connection timed out: connect
   > Could not download kotlin-annotation-processing.jar (org.jetbrains.kotlin:kotlin-annotation-processing:1.1.4-3)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-annotation-processing/1.1.4-3/kotlin-annotation-processing-1.1.4-3.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-annotation-processing/1.1.4-3/kotlin-annotation-processing-1.1.4-3.jar'.
            > Connect to akamai.bintray.com:443 [akamai.bintray.com/49.44.100.182] failed: Connection timed out: connect

**Comment by anthonycr** [comment]
kotlin version has been updated, please open another issue if you have a problem.
