### ISSUE TITLE
Why my Admob interstitial ads click not working in the code ?

### ISSUE THREAD

**Issue by KalpeshJadvani** [anthonycr/Lightning-Browser#628]
when open ad then close button is perfectly work ,  but on ad layout can't click  , i searched a lot but i couldn't  find any proper solution. So, can you give me reason ?  why this is happening....?

**Comment by anthonycr** [comment]
This issue has nothing to do with lightning browser, closing.

**Comment by vthinkmehul** [comment]
@KalpeshJadvani  solve your issue?
