### ISSUE TITLE
App crashes when typing in the address/search bar

### ISSUE THREAD

**Issue by Ploppy3** [anthonycr/Lightning-Browser#631]
App crashes when typing in the address/search bar.

- **Version:** premium.
- **Language:** French.
- **Search engine:** Google.
- **Keyboard:** Google Keyboard.
- **Android:** 8.0.0.

**Comment by anthonycr** [comment]
I'll investigate. Could you post a stacktrace if you can?

**Comment by Ploppy3** [comment]
I don't have Android studio installed and I don't know how to get it otherwise. If you know an other way to get the stack trace I would gladly do it.

**Comment by mufasa08** [comment]
anthony you should add analytics tool like crashalytics to track this easily

**Comment by Ploppy3** [comment]
The app don't seem to crash after the last Gboard update.
