### ISSUE TITLE
app closes when selecting items from search list

### ISSUE THREAD

**Issue by puppykickr** [anthonycr/Lightning-Browser#721]
I have an android 7.1.1

I use DuckDuckGo as a search engine, and have a bookmark with all my search engine settings as the homepage.

I have noticed that since I have been using android 7.1.1 on a ZTE 558 VL that when I make a selection from the search list, the app will immediately close unless I long press my selection, then choose 'open in new tab'.

The problem seemed to disappear after a few weeks (weird, right?), but has now returned.

Is there some way or setting I can use to eliminate this issue?

**Comment by puppykickr** [comment]
If anyone is interested, on a different thread I found that someone who had this problem remedied it by turning of 'allow sites to open new windows/tabs' in the app settings.

So far, it seems that the problem has all but disappeared.

I just started trying it out, and I am using both the regular Lightning and the 'bare bones' version.

I will comment more if the problem returns, but for now this seems like the solution to an annoying problem.

**Comment by Aufschlauer** [comment]
> If anyone is interested, on a different thread I found that someone who had this problem remedied it > by turning of 'allow sites to open new windows/tabs' in the app settings.

Thanks for sharing this work around...

**Comment by puppykickr** [comment]
It basically works.
By that, I mean sometimes.

The problem is that you can no longer get out of redirect ads by just 'x-ing' out the tab it is on.

This has led me to just go back to the old setting.

This requires a long press on selections to keep the app from crashing.

The long press is actually the best functional work around.

**Comment by puppykickr** [comment]
I am closing this issue, as the problem has been fixed with the recent updates.

Tank you for the excellent work on this amazing browser!
