### ISSUE TITLE
Tabs bar coverd by address bar.

### ISSUE THREAD

**Issue by ageback** [anthonycr/Lightning-Browser#741]
1. Settings - Display Settings - uncheck "Show tabs in navigation drawer"
2. back
3. Display as the screenshot

![image](https://user-images.githubusercontent.com/1097481/63006103-6a647200-beb0-11e9-9d26-be07d6514f10.png)

**Comment by puppykickr** [comment]
I do not have this issue, and am using DuckDuckGo as a homepage.

Also, why don't you use the tab drawer, as it is one of the unique features of the app?

If you desire, you can try Lightning Bare Bones version, which is available on F-Droid.

It puts the tabs on top by default, and I have never seen the searchbar deviate as you have shown.

**Comment by puppykickr** [comment]
I do not have this issue, and am using DuckDuckGo as a homepage.

Also, why don't you use the tab drawer, as it is one of the unique features of the app?

If you desire, you can try Lightning Bare Bones version, which is available on F-Droid.

It puts the tabs on top by default, and I have never seen the searchbar deviate as you have shown.

**Comment by ageback** [comment]
fixed in ver.5.0
