### ISSUE TITLE
Chrome unable to load video

### ISSUE THREAD

**Issue by ijurisic** [anthonycr/Lightning-Browser#785]
I try to open https://open.tube but respond is:
Dear Valued Customer, unfortunately you are using
Chrome version (77.0.3865.90) that contains (intentional?) critical Bug.
This Bug forbids you to watch ANY video on ANY PeerTube Instance.
Please use another browser or another version of Chrome.

https://github.com/Chocobozzz/PeerTube/issues/2132

Any chance to fix this problem?

**Comment by puppykickr** [comment]
@ijurisic 

It looks like you need to update another app on your device, called

Android System Webview

This is the system app on your device that allows Lightning and other apps to display web content.

You can get the update from alternative app stores or from the Google Play Store.

Personally I use ApkPure or UpToDown.

**Comment by puppykickr** [comment]
@ijurisic 

I tried the link above, using Lightning and the latest version of Android System Webview, and it works fine.
![Screenshot_2020-01-01_13-05-39](https://user-images.githubusercontent.com/44860287/71645138-46f06700-2c99-11ea-8468-d3ff11553830.png)

**Comment by puppykickr** [comment]
@ijurisic 

The current version of Android System Webview is

79.0.3945.93

**Comment by puppykickr** [comment]
@ijurisic 

Also, if you check through the comments on the other link you mentioned, you will see that this is the problem, and that issue has been closed quite a while ago.

**Comment by ijurisic** [comment]
Thanks lot on fast respond. I update my android os (LineageOS)  and now all is ok.
