### ISSUE TITLE
Alternative browser with swipeable tab and bookmark drawers?

### ISSUE THREAD

**Issue by estUser1** [anthonycr/Lightning-Browser#848]
What always made the Lightning browser so special to me were the swipeable tab and bookmark drawers. With Android 13, I get annoying certificate warnings when I use the Lightning browser, so I'm looking for an alternative. Is there a fork or something else with the same swipeable drawer functionality out there? Thanks :)

**Comment by Slion** [comment]
Try Fulguris

**Comment by estUser1** [comment]
Thanks for the response. Do I have to enable something to make the drawers swipeable? Can't find any option to enable it.

**Comment by Slion** [comment]
Settings / Look & Feel / Panels / Locked panels

**Comment by estUser1** [comment]
Good stuff. Thanks!
