### ISSUE TITLE
[Feature Request] More clear on exit options

### ISSUE THREAD

**Issue by revuwa** [anthonycr/Lightning-Browser#98]
It would be awesome to see some more options like the (advanced setting) 'Clear cache on exit'. 

I would love to see the two other points 'Clear history on exit' and 'Clear browser cookies on exit'. 

I don't know if there have to be single points for that, which overload the settings menu. IMHO some kind of sub point, like the midori (desktop) browser has, could do the trick:
![privacy](https://cloud.githubusercontent.com/assets/7300276/3552359/232b075c-08f6-11e4-9a18-40de8f7dcd66.PNG)

**Comment by BenFavoredSon** [comment]
Hi Dev,  

For some reason, long pressing the back button of my tablet Bauhn AT101-014 will not allow me to exit your browser. I also tried long pressing the back icon of your app right after the URL field and still in vain. 

Your app however allows me to exit when I 'X' all the tabs from the drawer.  My tablet is not really of good repute either.  I guess I really need to upgrade to a better tablet.  Still,  I think an exit   button that reconfirms if the user really wants to leave the app would be the best solution for users in my situation. Even better if this exit button is configurable in settings so it only shows up for users who need it. 

It's a 5-star app as app as it is and I won't take it against you if this feature won't make it to future iterations. It doesn't bother me too much really 😁.. 

Thank you for reading this Dev, 

B

**Comment by BenFavoredSon** [comment]
Hi Dev,  

For some reason, long pressing the back button of my tablet Bauhn AT101-014 will not allow me to exit your browser. I also tried long pressing the back icon of your app right after the URL field and still in vain. 

Your app however allows me to exit when I 'X' all the tabs from the drawer.  My tablet is not really of good repute either.  I guess I really need to upgrade to a better tablet.  Still,  I think an exit   button that reconfirms if the user really wants to leave the app would be the best solution for users in my situation. Even better if this exit button is configurable in settings so it only shows up for users who need it. 

It's a 5-star app as app as it is and I won't take it against you if this feature won't make it to future iterations. It doesn't bother me too much really 😁.. 

Thank you for reading this Dev, 

B

**Comment by BenFavoredSon** [comment]
Hi Dev,  

For some reason, long pressing the back button of my tablet Bauhn AT101-014 will not allow me to exit your browser. I also tried long pressing the back icon of your app right after the URL field and still in vain. 

Your app however allows me to exit when I 'X' all the tabs from the drawer.  My tablet is not really of good repute either.  I guess I really need to upgrade to a better tablet.  Still,  I think an exit   button that reconfirms if the user really wants to leave the app would be the best solution for users in my situation. Even better if this exit button is configurable in settings so it only shows up for users who need it. 

It's a 5-star app as app as it is and I won't take it against you if this feature won't make it to future iterations. It doesn't bother me too much really 😁.. 

Thank you for reading this Dev, 

B

**Comment by BenFavoredSon** [comment]
Hi Dev,  

For some reason, long pressing the back button of my tablet Bauhn AT101-014 will not allow me to exit your browser. I also tried long pressing the back icon of your app right after the URL field and still in vain. 

Your app however allows me to exit when I 'X' all the tabs from the drawer.  My tablet is not really of good repute either.  I guess I really need to upgrade to a better tablet.  Still,  I think an exit   button that reconfirms if the user really wants to leave the app would be the best solution for users in my situation. Even better if this exit button is configurable in settings so it only shows up for users who need it. 

It's a 5-star app as app as it is and I won't take it against you if this feature won't make it to future iterations. It doesn't bother me too much really 😁.. 

Thank you for reading this Dev, 

B

**Comment by BenFavoredSon** [comment]
Hi Dev,  

For some reason, long pressing the back button of my tablet Bauhn AT101-014 will not allow me to exit your browser. I also tried long pressing the back icon of your app right after the URL field and still in vain. 

Your app however allows me to exit when I 'X' all the tabs from the drawer.  My tablet is not really of good repute either.  I guess I really need to upgrade to a better tablet.  Still,  I think an exit   button that reconfirms if the user really wants to leave the app would be the best solution for users in my situation. Even better if this exit button is configurable in settings so it only shows up for users who need it. 

It's a 5-star app as app as it is and I won't take it against you if this feature won't make it to future iterations. It doesn't bother me too much really 😁.. 

Thank you for reading this Dev, 

B

**Comment by BenFavoredSon** [comment]
Hi Dev,  

For some reason, long pressing the back button of my tablet Bauhn AT101-014 will not allow me to exit your browser. I also tried long pressing the back icon of your app right after the URL field and still in vain. 

Your app however allows me to exit when I 'X' all the tabs from the drawer.  My tablet is not really of good repute either.  I guess I really need to upgrade to a better tablet.  Still,  I think an exit   button that reconfirms if the user really wants to leave the app would be the best solution for users in my situation. Even better if this exit button is configurable in settings so it only shows up for users who need it. 

It's a 5-star app as app as it is and I won't take it against you if this feature won't make it to future iterations. It doesn't bother me too much really 😁.. 

Thank you for reading this Dev, 

B
